### ISSUE TITLE
Can't submit link with > 2 links as new user

### ISSUE THREAD

**Issue by alexander-morris** [oceanprotocol/oceandao#1]
I was just trying to submit my proposal with all the social links for the bios, it won't let me. 

I've submitted it without the links for now. 

![image](https://user-images.githubusercontent.com/37120777/100951584-3833b500-34e5-11eb-8d29-d0e6b2b5590e.png)

**Comment by w1kke** [comment]
I edited the settings in port so you can now add 20 links as a new user.

**Comment by trentmc** [comment]
This seems to be solved. Therefore closing. Please reopen if it's still an issue.
