### ISSUE TITLE
[DAObot] Bug: Unused earmark funds are going to treasury for future, should be going to general in current round

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/oceandao#119]
**Describe the bug**

Summary: 
- It appears that in DAObot, unused earmark funds are going to treasury for future funding rounds. This is incorrect. 
- What's correct: unused earmark funds go to general grants for that funding round.
- It's important to fix ASAP so that R13 projects can get the funding as available

Details: [Robin](https://github.com/w1kke) reported the error [here](https://github.com/oceanprotocol/oceandao/issues/75#issuecomment-1007342598). Copying his text:

> @trentmc but if I look at the implementation in the current round on Ocean Pearl (https://oceanpearl.io/dao-voting - in the top) then I see that this is not happening.
>
> The funds are getting burned/returned to treasury because an earmark is not fully filled instead of going back to the general category. This means that projects will not get funded in this round.
I am just trying to understand whether I am misunderstanding something or the system has a flaw right now - it would be important to catch this now so that projects can get the funding if it is available.
>
> Quote from the Ocean Pearl Discord:
>> Maka | Ocean Pearl — Today at 11:49 AM
>> Hello @robin (alpha.DataUnion.app) ,
>> this round we are having a smaller grantpool overall, so not all proposals will receive a funding, even 
>> if all proposals would have been upvoted.
>> In addition to that, the overall pool is also split into a "general" pool and separate "earmark" pools 
>> that are only eligible for marked proposals.
>> For your example, the proposal is only eligible for the "general" pool, which is depleted, it needs 253 
>> votes to get ahead of the proposal with the lowest effective votes, that still got funding from the 
>> "general" pool.
>> The burned tokens are from an earmarked pool.
>> Maka | Ocean Pearl — Today at 12:07 PM
>> I hope this cleared things up a little

**Expected behavior**
Unused earmark funds should go to general grants for that funding round.

**Additional context**

Here is correct overall behavior. There are two steps of recycling.
1. If funds inside an [x] earmark are not fully utilized, recycle to [General Category] for that funding round. (Decided by Params&Roadmap WG in github issue [#75](https://github.com/oceanprotocol/oceandao/issues/75)).
2. If funds in [General Category] for a funding round are not fully utilized recycle to Treasury for future rounds. (Decided by Params&Roadmap WG in github issue [#49](https://github.com/oceanprotocol/oceandao/issues/49)).

**Comment by trentmc** [comment]
Message from @trizin 

> Hey there, thanks for creating the issue. > https://github.com/oceanprotocol/DAOBot/pull/99
> This PR was merged 8 days ago I think it solves the issue. With this PR, unused earmark funds should go to general grants this round.

@trizin could you reconcile what the intent of the PR is, with the issue reported by Robin please?

**Comment by trizin** [comment]
I think this issue has been resolved.

#### Changes in https://github.com/oceanprotocol/DAOBot/pull/99
- Unused earmark funds go to general grants.
- If there is a proposal that is not in the general category and not funded, it will be included in the general category.

Changes will take effect from the 13th round.

**Comment by w1kke** [comment]
I think then it is more a problem of OceanPearl? If you look at their header then still tokens are supposed to be burned but that should not happen as there are projects that are not getting funded (see the second screenshot). Maybe I am just not understanding a fundamental principle here but in the case that there are projects that want to get funding there should be no burn happening under the current rules.
<img width="1242" alt="Screenshot 2022-01-08 at 11 54 19" src="https://user-images.githubusercontent.com/921146/148641521-d2ed9a4e-573a-4868-8a3a-e764f25aac38.png">
<img width="1223" alt="Screenshot 2022-01-08 at 11 55 24" src="https://user-images.githubusercontent.com/921146/148641558-459b4fc4-fc5f-4c50-995b-710138d8f490.png">

**Comment by KinimodEtlon** [comment]
This is a problem on our end, we were under the impression that this mechanism would not be used for this round. We will try to fix this ASAP. I created an issue for this https://github.com/ocean-tech-ship/ocean-pearl-api/issues/233 , i am not sure how long it will take to fix this.
