### ISSUE TITLE
Fund project in descending order on the basis of USD at the time the vote ends

### ISSUE THREAD

**Issue by TimDaub** [oceanprotocol/oceandao#121]
## Scope
<img width="658" alt="Screen Shot 2022-01-11 at 13 41 17" src="https://user-images.githubusercontent.com/2758453/148944366-4d56186f-6425-40af-92da-4cfaddad07c1.png">

- Some OceanDAO participants are surprised of not receiving funding in R13, see above screenshot and resulting conversation around this timestamp: https://discord.com/channels/612953348487905282/776848812534398986/930441035023282187
- OceanDAO commits monthly a fixed number of OCEANs to each round, e.g. in R13 200k OCEAN
- All projects then request funds in USD in their proposals
- On the day the due diligence process starts, OceanDAO stores the latest OCEAN/USD price.
- For the resulting vote tally, each project, in a descending order, then receives the amount of OCEAN that they requested in USD given the price of OCEAN/USD at the day the due diligence process started
- The problem with this approach is that the due diligence process date and the vote ending date are far apart and in the past lots of volatility occurred in the OCEAN/USD market. E.g. for RPI in R12, this meant that the OCEANs sent were worth 4k USD less than what we requested.
- I'd even go as far as saying that there's a fair amount of manipulation in the market going on as when invoices are paid, OCEANs may be bought at a discount (as DAO participants have selling pressure to cover operational costs).

## Deliverables

- To address this problem partially, I've opened #81 
- However, additionally, I think it'd be beneficial for everyone if the time when the OCEAN/USD price is recorded is the time the vote ends.
- In that case, once the vote ends the algorithm gets the current OCEAN/USD price. Given now this specific amount of USD the OceanDAO algorithm can allocate, it starts from the top to bottom and funds all projects + all earmarks until the OCEANs (that we're calculating with as USD) are depleted.

## Note

- Before anyone misunderstands things in this issue. All I'm arguing for is to shift the day when the OCEAN/USD price is stored to exactly the moment when the vote changes. The benefit of it is that then each project that'd get funding, would get the best possible price for their OCEANs in USD which then also most accurately reflects the amount of funding they requested in the first place.

**Comment by TimDaub** [comment]
duplicate of #120

**Comment by idiom-bytes** [comment]
Thank you for taking the initiative to write & close this issue Tim!
