### ISSUE TITLE
Update SpringDAO snapshot space to use the monolithic strategy

### ISSUE THREAD

**Issue by LoznianuAnamaria** [oceanprotocol/oceandao#123]
#### Considered Deliverables:
- [ ] Custom BrightID network (Polygon) to provide support 
We agreed on not delivering this work as it is additional effort, and upfront optimization before we release the current goals that we have outlined. Let's increase the rate for how we: [ship, measure, learn] and THEN, improve.

#### DoD:
- [x] We have already implemented the monolithic strategy as well
- [x] We are using the demo.snapshot now instead of SpringDAO
- [x] We are leveraging the existing officialoceandao.eth ENS

**Comment by idiom-bytes** [comment]
I believe this task is now completed.
