### ISSUE TITLE
Discuss and identify funding approaches for the PGWG

### ISSUE THREAD

**Issue by idiom-bytes** [oceanprotocol/oceandao#129]
R13 - Reward Structure & Proposal
------------------
We set a buget for the round = example (1000 Ocean)
We have members w/ 100 GIVE each = example (5 members * 100 GIVE)
Members then assign GIVE to each other based on contributions
Each GIVE is then worth ~= (1000 OCEAN / 500 GIVE) = ~2 OCEAN/GIVE

Prakash + Scott to discuss this, and provide a proposal for R13 Epoch.

**Comment by idiom-bytes** [comment]
https://discord.com/channels/612953348487905282/908016658239610920/931508074836004905

> From Prakash
> 
> Hello Roberto, I had a good discussion with Scott on how this could be done. After initial difficulties in terms of how we could figure this out we've come up with a structure that can be applicable across any EPOCH. We couldn't decide based on hours, but decided that we could judge based on the number of Work done, Calls attended that could proportion to a possible GIVE Multiplier/bonus?
> 
> Ocean Budgeting:
> 
> We believe the budget for review should be set at 500 Ocean for every 10 reviews in total per round. Given that we received a total of 31 proposals this round, we estimate the budget churn for R13 at 1550 Ocean for this.
> 
> Part I - Budgeting formula 
>  
> A suggested formula for assuming the quantum of work is as below
> 
> Proposal welcomed/check-listed at 40% $Ocean quantum per proposal
> Proposal Reviewed at 60 % $Ocean quantum per proposal
> 
> In short, a budget of 0.4 + 0.6 multiplier for Welcome + Review ~ towards the total of 50 per overall review
> 
> Anything additional to the Review process $ocean budget is based on the GIVE Budget (Assuming we have 500 $Ocean for specific criteria)
> 
> Part II - Summary of our Work
> 
> Giving you a summary of our work so you have a good chance to decide how its worked out.
> 
> Prk: 
> 
> - Proposals welcomed - 10
> - Proposals reviewed - 1
> - Calls attended: 4
> - Video series on PG-WG Minutes
> 
> Scott:
> 
> - Proposals welcomed - 2
> - Proposals reviewed - 2
> - Calls attended: 3
> - Audit of the PG-WG document (edited)
> 
> Part III - GIVES
> 
> We believe the FINAL GIVE criteria could be based on the following:
> 
> * Quality of reviews
> * Quality of activities done outside of reviews
> * Chief coordinape GIVE-R discretion
> 
> ----
> 
> In terms of the budget split. we have some ambiguity. Assuming that we have a 500 ocean budget for this EPOCH based on GIVES, We have the following concerns. 500 GIVEs are available however we have only 3 active GIVERs at the moment. Is the GIVE going to be a multiplier of sorts? or an $Ocean bonus on top of the base review activity
> 
> Lead Coordinape: Idiom
> 
> Active coordinapes:
> 
> Prakash
> Scott
> 
> On-the-fence Coordinapes:
> 
> Trang (awaiting self-assessment)
> Mnkytigr
> 
> --
> 
> Gross calculations are not finalized until after initial review from you @Idiom | Ocean

**Comment by idiom-bytes** [comment]
> Hi Prakash, thanks for the awesome summary.
> 
> Having an estimated cost per review makes sense, I believe it provides a basic unit to estimate a budget per round.
> Example: @ 30 proposals (@50 / full guidance) ~= Available funds >> 1500 OCEAN. 
> Proposal: 100% of available funds should only be distributed only after all proposals receive full support.
> 
> Due to the amount of manual work required to properly review a project, and the organic nature of Coordinape, we might want to consider how to balance both.
> 
> Example:
> 50% of rewards are paid transactionally (measurable key activities)
> 50% of rewards are paid organically (measurable and intangible activities)
> 
> This would mean that if a guide provided full support for 10/30 proposals, they would get paid a base fee of 250 OCEAN + a remainder based via Coordinape circle.
> Proposal: I believe that guides should have a maximum # of proposals they can support. At that point, they should focus on other activities such as growing the circle, improving the process, or helping each other.
> 
> By structuring things in this manner, we can rebalance the transactional and organic rewards as the PGWG evolves.
> 
> I do want to point out that transactional activities == bookeeping.
> Hopefully the guidance tracker can solve this problem without any additional overhead.
> If overhead does increase, I would promote the WG fight that urge and instead lean heavier towards Coordinape (or Sourcecred).
> 
> WRT to your breakdown.
> 
> Part 1:
> - I agree that welcoming participants is a very important step, but I do want to identify that without a "Review" conversion this can be gamed (i.e. not really worried about this right now). Did you two consider this in your conversations?
> - So, Guides should perhaps consider how to balance the "Welcoming" part, by focusing more on having participants writing & submitting a proposal so it can be reviewed.
> 
> Part 2:
> - It's great to see a "contribution summary".
> - I'm wondering how the calls went? One concern I have with calls is that they don't scale well and carry the risk that "something was said in the call and no one can verify"... or that "there was this great piece of information shared but we can't refer to it". If the group believes calls are valuable, I propose guides consider recording + sharing these in the open (put link to call inside Guide Tracker).
> 
> Part 3:
> I agree, the "Final Give" criteria looks great. I believe the following are also valuable activities:
> - Onboarding new Guides
> - Improving the process/documentation/videos (this one seems a bit harder to measure/reward) 
> [GIVE : Ocean Ratio]
> To answer your final question "GIVES as multipliers", yes, this is how they would work.
> - Each participant that completed the epoch successfully is assigned 100 GIVES.
> - Participants can provide GIVES to each other, or not.
> - At the end, total GIVES per Participant is calculated, generating a .csv.
> - We can then calculate the rewards such as: calculateRewards(give_distribution.csv, total_ocean_rewards)
> 
> If:
> Proposals = 30
> Ocean / Proposal = 50
> GIVES = 300
> 
> Then:
> Total Available Ocean = 1500
> Ocean / GIVE = 5
> 
> If only 50% of rewards go toward Coordinape, then
> (Ocean / GIVE) * 0.5 ~= 2.5 OCEAN per GIVE

**Comment by idiom-bytes** [comment]
### Reward Target:
I believe 50 Ocean (est. ~$1) / Fully researched & completed review (i.e. review journey) seems like a good starting, competitive target.

I believe we should promote this group to increase quality of review & process as much as possible, without it being necessarily a mined activity.

Example:
1. First increase quality & value generated
2. Then fund retroactively

### Designs considered
- 40/60 Welcome-Review Split (1)
- Transactional  (2) - reward per completion vs. Organic (3) - reward 100% via coordinape
- How to Balance other Activities (4) such as improving documentation, doing videos, onboarding new participants
- How to Organize Budget (5) for this round example: We didn't complete the 1550 Ocean (31 reviews) worth of work. 

I lean that:
(1) May be rebalanced a bit so it's not gamed.
**(3) I believe the more rewards distributed via GIVE, the more emergent activities we'll discover (4).**
(5) Budget/Rewards should be set based on welcome / completion ratio

**Comment by drprk** [comment]
> Having an estimated cost per review makes sense, I believe it provides a basic unit to estimate a budget per round.
> Example: @ 30 proposals (@50 / full guidance) ~= Available funds >> 1500 OCEAN.
> Proposal: 100% of available funds should only be distributed only after all proposals receive full support.

I agree. Hence I had put forth a structure where due to the deficit of the PG-WG members for this round, the complete funds must not be Utilized, hence we are talking along the lines of a Pro-rata system, given that we might always see such a system in future. Hours of work is very hard to judge and discrepancy hence we had discussed the acceptable Quantum of work at 50/proposal.

> 
> 50% of rewards are paid transactionally (measurable key activities)
> 50% of rewards are paid organically (measurable and intangible activities)

I agree with this structure, can solve a lot of abstraction that is involved.

> Proposal: I believe that guides should have a maximum # of proposals they can support. At that point, they should focus on other activities such as growing the circle, improving the process, or helping each other.

This is cool. However this can be decided at the start of the EPOCH + Also adjusted mid-way during the EPOCH, given that the priority should be to ratify the max proposals possible and not gate-keep a lot of potential evaluation that's possible. But a fair split/range is fine. 

> I do want to point out that transactional activities == bookeeping.
> Hopefully the guidance tracker can solve this problem without any additional overhead.
> If overhead does increase, I would promote the WG fight that urge and instead lean heavier towards Coordinape (or Sourcecred).

Yes, I think we can have a short feedback on why the Guidance tracker might have received lesser entries, but reducing the steps involved as suggested earlier puts us on track so there's lesser visual friction to REVIEW proposals.

----------------------------------------------------

**Breakdown mechanics:**

> Part 1:
> 
> I agree that welcoming participants is a very important step, but I do want to identify that without a "Review" conversion this can be gamed (i.e. not really worried about this right now). Did you two consider this in your conversations?
> So, Guides should perhaps consider how to balance the "Welcoming" part, by focusing more on having participants writing & submitting a proposal so it can be reviewed.

Agree with those concerns, but I think Welcome also involves checking for deliverables checklist, that requires a lot more due diligence and strain involved.

**Rebuttal:**

Welcome-Review ratio for New proposals: 20-80 ratio
Deliverable checklist - Review ratio for Older proposals: 40-60

> Part 2:
> 
> It's great to see a "contribution summary".
> I'm wondering how the calls went? One concern I have with calls is that they don't scale well and carry the risk that "something was said in the call and no one can verify"... or that "there was this great piece of information shared but we can't refer to it". If the group believes calls are valuable, I propose guides consider recording + sharing these in the open (put link to call inside Guide Tracker).

I will admit that I didn't think this through. We need to see audit of calls & summary activities to reflect well here. At the moment I don't have any audit from the calls apart from the reference document that is with you. Maybe some attention can be given to this. 

Link to call recordings are fine but they don't scale well in terms of ppl actually referring to it. What people might love of course if u might set aside independent budgets for Call-audits and summary (given that it might be too stressful for you to log them all the time). 

**Expectation of audits:** Nothing too fancy, just the 5-6 line effective summary of the call and a 3 point Action station summary

> Part 3:
> I agree, the "Final Give" criteria looks great. I believe the following are also valuable activities:
> 
> Onboarding new Guides
> Improving the process/documentation/videos (this one seems a bit harder to measure/reward)
> [GIVE : Ocean Ratio]
> To answer your final question "GIVES as multipliers", yes, this is how they would work.
> Each participant that completed the epoch successfully is assigned 100 GIVES.
> Participants can provide GIVES to each other, or not.
> At the end, total GIVES per Participant is calculated, generating a .csv.
> We can then calculate the rewards such as: calculateRewards(give_distribution.csv, total_ocean_rewards)

No objections here. All points are important.

**Comment by drprk** [comment]
> **Reward Target:**
> I believe 50 Ocean (est. ~$1) / Fully researched & completed review (i.e. review journey) seems like a good starting, competitive target.
> 
> I believe we should promote this group to increase quality of review & process as much as possible, without it being necessarily a mined activity.
> 
> **Example:**
> 
> First increase quality & value generated
> Then fund retroactively

Agree there. But, occasionally we need to do a bit of growth-hacks whenever it is needed, while maintaining processes.

> **Designs considered**
>
> 40/60 Welcome-Review Split (1)
> Transactional (2) - reward per completion vs. Organic (3) - reward 100% via coordinape

Transactional (50%) + Coordinape GIVE-multiplier would be fine (50%)

> How to Balance other Activities (4) such as improving documentation, doing videos, onboarding new participants
> How to Organize Budget (5) for this round example: We didn't complete the 1550 Ocean (31 reviews) worth of work.

It's alright that we only have the pro-rate of budget consumed given that we didn't complete the REVIEW proposals for previous round, unless you propose an alternative. The coordinape partition of 50% can still account for the pro-rata of quality work done by PG-WG members.

> **I lean that:**
> (1) May be rebalanced a bit so it's not gamed.

Proposed an adjusted split in the previous comment.

> (3) I believe the more rewards distributed via GIVE, the more emergent activities we'll discover (4).

Wouldn't agree completely with this until people get completely familiar with coordinape. It took me a discussion with Scott to have him familiar with the concept too.

> (5) Budget/Rewards should be set based on welcome / completion ratio

To be noted that Welcome for an older proposal has a lot more teeth to it given that we have to add check-list of deliverables.

**Comment by idiom-bytes** [comment]
Here is are the proposed actions so we can complete this task.

#### As discussed in the WG meeting today:
- Paying out in a transactional manner adds a lot of overhead
- Time spent bookeeping/accounting can be spent instead delivering value
- The more value we deliver, the more rewards we can pay out to the WG

#### Proposal for improving process:
- Do 100% of funding via Coordinape
- Measure impact (rather than value) per activity to direct outcomes
- [Create an "Activity Summary" spreadsheet](https://github.com/oceanprotocol/oceandao/issues/130) so Coordinape GIVE members can more easily assign value

#### Other Proposed Improvements:
- We have rolled some of the proposed improvements here back into our **Outline** + **Guide** + **Roadmap**
- If there are any other improvements to be made, please move them from this issue back into our tools mentioned above

#### Proposal for finalizing this ticket:
- Estimated 460 Ocean to be paid out based on activities delivered.
- 100% of this amount will be paid out via Coordinape GIVE
- Calculations can be found below.

![Screenshot from 2022-01-20 09-20-00](https://user-images.githubusercontent.com/69865342/150389365-651a44dc-8859-4c3a-b4c6-315675ea9de3.png)
