### ISSUE TITLE
Create Activity Summary for making decisions in Coordinape

### ISSUE THREAD

**Issue by idiom-bytes** [oceanprotocol/oceandao#130]
As per Prakash's suggestion, it's currently hard to measure Guide contributions, and make decisions towards Coordinape rewards.

Future Improvements:
- [ ] Expand the activities inside of Guidance Tracker so participants can share other deliverables (in the future): twitter storms, video reviews, etc.. 

### DoD:
- [ ] Build "Activity Summary" sheet that summarizes work delivered in the Guidance Tracker

**Comment by drprk** [comment]
- Close to the end of each EPOCH; we await a personal audit summary
- Submit Personal Audit Summary from each PG-WG Guide
- The Audit summary will adapt suitable takeaways from the previous discussions

https://github.com/oceanprotocol/oceandao/issues/129

- Build Activity Summary sheet for each EPOCH
- Gross Funds allocated per Epoch 50 Ocean per proposal
-  100% payout via Coordinape GIVES
