### ISSUE TITLE
R15 [OceanDAO Eng WG] Prepare Round - Google Schedule

### ISSUE THREAD

**Issue by LoznianuAnamaria** [oceanprotocol/oceandao#136]
**Add round events in the [cean Ecosystem Calendar](https://oceandao.notion.site/Ocean-Ecosystem-Calendar-4cefa1944a314128afd2ae0ea1a04eb6)**
- [x] OceanDAO - GR15
 - Period: 2022-02-07T23:59:00.000Z - 2022-03-01T23:59:00.000Z
 - Description: Link to [port round](https://port.oceanprotocol.com/c/oceandao/round-15)
 - [x] R15 Last Week to Submit
- Period: 2022-02-22T23:59:00.000Z - 2022-03-01T23:59:00.000Z
- Description: Get your proposal submissions in place!  https://oceanprotocol.com/dao
- [x] R15 Due Dilligence
- Period: 2022-03-01T23:59:00.000Z - 2022-03-03T23:59:00.000Z
- [x] R15 Voting Period
- Period: 2022-03-03T23:59:00.000Z - 2022-03-07T23:59:00.000Z
- Description: Cast your vote - link to the voting notion page.
- [x] R15 Last Day to Vote
 - Period: 2022-03-06T23:59:00.000Z - 2022-03-07T23:59:00.000Z
 - Description: Last day to get your votes in place!

**Comment by idiom-bytes** [comment]
Thank you so much for setting this up Norbert!!

It was great to see that this was already done!

Please feel free to close this issue.
