### ISSUE TITLE
R15 [OceanDAO Eng WG] Prepare Round - Site

### ISSUE THREAD

**Issue by LoznianuAnamaria** [oceanprotocol/oceandao#138]
**Update [site](oceanprotocol.com/dao) with**:
 - [x] Proposals submissions deadline: 2022-03-01T23:59:00.000Z
- [x] Round 15 funding available
- [x] Voting period : 2022-03-03T23:59:00.000Z - 2022-03-07T23:59:00.000Z
 - [x] Merge & deploy the PR

**Comment by idiom-bytes** [comment]
Hi, it was great to see this completed. Thank you so much for your help Norbert!

Happy if you close it.
