### ISSUE TITLE
Pinning OCEAN price to date at due dilligence and having projects in USD doesn't help stabilize the funding amount

### ISSUE THREAD

**Issue by TimDaub** [oceanprotocol/oceandao#14]
See wiki page: 

> PLEASE NOTE: The amount requested is in USD, but the amount paid is in OCEAN token. The conversion rate is the market price on the given Round's Proposal Due By Deadline. This determines how many OCEAN will be awarded if a proposal is voted to receive a grant. This is done automatically and updated in our Funding Rounds Airtable.

However, in e.g. Round 9 the problem is that OCEAN on Due By Deadline date was 0.77 OCEAN/USD. Today it's 0.68 OCEAN/USD, so it's 9 cents lower. That's an (0,77-0,68)/0,77*100 = 11,68% pay cut some projects have to suffer. Additionally, it's unclear in what order and priority that projects get payouts.

I've picked projects at random and checked their payout dates:

- Sep-18-2021 09:41:09 AM +UTC https://etherscan.io/tx/0xb1af100ffaa895b7adbcd000bab2ae1eede8920ea986ad7d98d0a491373f965e
- Sep-19-2021 05:10:13 PM +UTC https://etherscan.io/tx/0xc09348d4ae13c80c855a96fa3ec47891cf0accd6e685ed94fb821f4c1c4fb6ad

Considering the volatility of the market currently and the fact that projects are expected to deliver on a set of deliverables, I find this way of handling the actual funds quite irresponsible. Not only can this cause problem to the projects' budget allocations - on the OPF side it's also simply burning a lot of potential USD that could have been spent more usefully.

Here's what I suggest:

- Pay all projects at the same time. If you have to check the validity of invoices; check it all at the same time; then click on payout.
- Find a process that better captures the actual OCEAN/USD price or that minimizes the error in USD payout. Deadline Due date is very early and captures true price badly.

Additionally, incumbent projects can protect their funding amounts by calculating a statistical error based on the methodology outlined in this section: https://github.com/rugpullindex/documents/blob/master/handbook.md#how-we-calculate-the-amount-of-funds-requested-on-ocean-dao-proposals

**Comment by idiom-bytes** [comment]
@trizin @trentmc 
Hi, I believe this issue has been mostly addressed.

In the future we'll be automating this further to reduce the lag even more.
I propose we close this ticket.
