### ISSUE TITLE
R15 Proposals Updates - Live-OPS

### ISSUE THREAD

**Issue by LoznianuAnamaria** [oceanprotocol/oceandao#140]
- [x] Review port for proposal updates
 - [x] Update proposals deliverable checklist inside airtable

**Comment by idiom-bytes** [comment]
Most of this work should be handled by the portal now.
The script should be updated to reflect the need to provide review & accept completed proposals

Example:
- [x] Review/Accept/Reject "Completed Proposals" in Proposal Admin portal
- [x] Review/Accept/Reject "Core-Tech" Earmarked proposals
