### ISSUE TITLE
R15 Conclusions - Finance Transactions

### ISSUE THREAD

**Issue by LoznianuAnamaria** [oceanprotocol/oceandao#150]
- [x] Generate hash keys for the winners
- [x] Fund the contract that automatically distributes the funds
- [x] Burn remainder

**Comment by idiom-bytes** [comment]
We have some pending transactions that need to be addressed.
- Both FitCoral and talentDAO are legit projects.
- FitCoral, is a returning project.
- Pearl will be claiming separately as well.

We have a few tactics that we're organizing from the comms side:
[Grantee Email Reminder](https://github.com/oceanprotocol/oceandao/issues/188)

I hope we can flesh out some of these improvements before enforcing dates.

**Comment by trentmc** [comment]
> Burn remainder

We don't burn anymore. We "put back in the treasury for future rounds" which, practically speaking, means "no extra action needed".

**Comment by idiom-bytes** [comment]
These are the 3 projects that still require funding to be completed. Close task after.
- [ ] talentDAO
- [ ] FitCoral
- [ ] Pearl

**Comment by malvonme** [comment]
Pinged daniel to ping me when all 3 invoiced -> and got their grants.

**Comment by malvonme** [comment]
**Update:** 
- TalentDAO received their grant through Request
- OceanPearl received their requested amounts
- FitCoral also is marked as funded by now (Screenshot)

#Closed![Bildschirmfoto 2022-04-13 um 22.47.12.png](https://images.zenhubusercontent.com/6230bfd994a5cba772c63765/8a549c0f-77ca-49db-a958-efcc2f266c44)
