### ISSUE TITLE
Project with Grant Category "Build & integrate" is appearing in "New Outreach" 

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/oceandao#152]
**Describe the bug**
See image. The top row shouldn't be here since it's not "Outreach"
![earmarked](https://user-images.githubusercontent.com/5305452/152811374-57976b75-19b5-4913-b07c-5e3cfc7ea1cf.png)

**To Reproduce**
Go to Round 14 voting page and you will see.

https://oceandao.notion.site/Round-14-Votes-b2a854feaceb4393af3909684c065dbe

**Comment by idiom-bytes** [comment]
![Screenshot from 2022-02-07 07-24-54](https://user-images.githubusercontent.com/69865342/152817695-8a2ce6af-9a6e-4e47-ad01-8ecfcdb4ea25.png)

Fixed.
