### ISSUE TITLE
BSC ERC-20 is not counting correctly towards strategy

### ISSUE THREAD

**Issue by idiom-bytes** [oceanprotocol/oceandao#159]
Snapshot is unable to retrieve the information from BSC chain, although it's the same implementation.
About 2800 holders on BSC
https://www.bscscan.com/token/0xDCe07662CA8EbC241316a15B611c89711414Dd1a

Marketplace is very low liquidity
https://market.oceanprotocol.com/search?sort=created&sortOrder=desc

Only 14 datasets, with the highest one with 2,500 OCEAN

**Comment by trizin** [comment]
This has been fixed in the latest version of the strategy
