### ISSUE TITLE
[WEEKLY, Mondays/Tuesdays] Town Hall setup

### ISSUE THREAD

**Issue by KatunaNorbert** [oceanprotocol/oceandao#169]
- [x] Create TownHall and all WG events
- [x] Create TownHall presentations inside of drive (Mondays)
- [x] Share TH presentation internally ahead of time for others to edit (Mondays)
- [x] CTA Slack/ODAO, last chance to edit the deck for Town Hall (Wednesday Mornings)
 - [x] Update TownHall page with the presentation
 - [x] Share TH "event happening in the next 1 hour" internally + with community ahead of time
 - [x] Update TownHall page with the recording once it's available to be shared
- [x] Update TownHall page with at least 2 new events (future)

**Comment by idiom-bytes** [comment]
Made some small updates to include additional details:
https://github.com/oceanprotocol/DAOBot/pull/158

- [ ] Update TH presentations to be contextual to the Round {{ROUND_NUMBER}} Ops - Starting, Completing, Winners, Etc...
- [ ] Create TownHall event inside Discord Events.
- [ ] Record Town Hall.

**Comment by malvonme** [comment]
Townhall "Page":
https://github.com/oceanprotocol/oceandao/wiki/OceanDAO-Town-Hall
