### ISSUE TITLE
[Voting][Turnout][Delegation] Implement delegation inside Snapshot via Gnosis Delegate Registry.

### ISSUE THREAD

**Issue by idiom-bytes** [oceanprotocol/oceandao#17]
Motivation
An OceanDAO KPI is getting more OCEAN voted.

Solution
If people aren't willing to take the time to vote themselves, then at least they can defer to others. This is common, it's the idea of liquid democracy

One might worry that this is too much power in a smaller number of hands. In practice, anyone who worries about this can simply vote on their own rather than delegating. And it’s better than the tokens not voting at all: there’s a trust signal from the delegator to the steward.

Snapshot has added support for delegation via Gnosis Delegate Registry.
https://docs.snapshot.org/guides/delegation

**DoD:**
- [x] Setup Gnosis Delegate Registry
- [x] Configure Snapshot to utilize Gnosis Delegation
- [x] Configure Bob to delegate to Alice
- [x] Verify inside Test proposals that Alice total voting score = Alice + Bob

**Comment by trentmc** [comment]
While I like this idea, it's not a priority compared to the stories in the public roadmap. Eg qv. Let's invest our time accordingly.
