### ISSUE TITLE
Improve grant collect UX/Messaging on site.

### ISSUE THREAD

**Issue by idiom-bytes** [oceanprotocol/oceandao#177]
### Problem:
Web3 Tools - Grant Collect - Messaging can confuse users

> Just checked the history on the wallet I signed with and don't see one. I remember seeing a confirmation but seems it may have failed. The app was redirecting me to Rinkeby despite being connected to mainnet. It displayed the request to connect to mainnet, but would bring up a network switch request in metamask pointing to Rinkeby. I wasn't sure if the signatures were on testnet to avoid gas or something. Retrying now and it worked on mainnet. 

### DOD:
- [x] [All updates should be deployed on ocean/site](https://github.com/oceanprotocol/site/issues)
- [x] Are prompts/messaging/etc configured properly in production?

**Comment by KatunaNorbert** [comment]
Is this a recent issue? 
We have the switch to Rinkeby while we were on a staging state but we changed it after.

**Comment by idiom-bytes** [comment]
Yeah =(
https://discord.com/channels/612953348487905282/908016934161879080/951546285368942612

I proposed we deploy /site/ into staging.
This might help stabilize any web3 related things. =)

**Comment by KatunaNorbert** [comment]
We have everything pointing to mainnet, not sure how he was able to get messages related to Rinkeby.
