### ISSUE TITLE
[PGWG] Complete 3rd Coordinape circle & payout.

### ISSUE THREAD

**Issue by idiom-bytes** [oceanprotocol/oceandao#178]
Complete tasks for PGWG
https://discord.com/channels/612953348487905282/908016658239610920/951521004767805511

**Comment by malvonme** [comment]
Notified all potential guides in Discord Channel for Coordinape Kickoff next week WG call. 

When you set the Excel and sent out Epoch 1-3 to its members, feel free to move it to Review/QA. 

I will unassign myself from this now. 

I think the Coordinape basics now, am an admin to this circle, rest will come in demo next week (and sync between us). 

Thx!
