### ISSUE TITLE
Improve Voting Power View

### ISSUE THREAD

**Issue by idiom-bytes** [oceanprotocol/oceandao#179]
Make Voting Boost UX/UI More Generic
- Rebrand parts of Voting Boost to -> Voting Dashboard
- Make it easy to see delegates, and other information. Show the vote boost more granularly. Break it down.
- Boosts are just 1 more thing in here

### DOD:
- [ ] New view inside of website shows your Voting Power broken down granularly.

**Comment by KatunaNorbert** [comment]
Delegations from snapshot subgraph:
https://thegraph.com/hosted-service/subgraph/snapshot-labs/snapshot

**Comment by idiom-bytes** [comment]
Robin is reporting an issue with the frontend of the our web3tooling.
https://github.com/oceanprotocol/oceandao/issues/196#issuecomment-1081717796

We have experienced issues with the ocean subgraph where it is not fully up-to-date and sync'd with the latest block. Based on our estimates, it takes roughly 10 blocks for the subgraph to be updated. Therefore, we may want to reconsider our calculations so that they take place against (latestBlock - ~10).

Perhaps by updating this, we may be able to retrieve the right information inside of the FE portal.

This is the best hypothesis we have at the moment.

**Comment by KatunaNorbert** [comment]
There is a fix here for the above issue: https://github.com/oceanprotocol/site/pull/1431

**Comment by idiom-bytes** [comment]
@idiom-bytes please review PR
