### ISSUE TITLE
[Idea] As voter; allow signalling max fund allocation per project

### ISSUE THREAD

**Issue by TimDaub** [oceanprotocol/oceandao#18]
This is merely an idea that I wanted to document somewhere; so I chose to open an issue in this repo. Here we go:

Since a few rounds, projects can set a "funding request" per proposal. However, voters can only vote "YES" or "NO" given the project's funding amount suggestion.

Personally, I look at the vote a bit differently. I'm aware of the vote tally and I know that the last projects might get less or no funds. Sometimes, I'd like to vote "YES" for a project in general because I believe in their team; however, it might be that their funding amount is dramatically off.

Especially for new projects; if I had the voting power; I'd signal that their max funding amount is only 5k USD in most cases.

Hence, allowing voters to supply a "max funding amount" when voting with their OCEAN as voting credits, it'd be interesting for two reasons:

- voters could directly "design" the order and allocation of all funds; e.g. they could design to lower the top funds to spread more to the bottom or vice versa
- voters could make individual adjustments to specific projects that they'd like to support but with an adjusted funding amount.

As an optional addition; the funding amount field could even allow the voters to increase a project's funding amount too.

**Comment by anapheys** [comment]
Thanks for the comments Tim - noted!

**Comment by trentmc** [comment]
This is done. People can now signal with an amount of OCEAN allocated per project. Both positive and negative signals.
