### ISSUE TITLE
Build #Amplify channel on Discord so community can share particular news that they want OceanDAO + OPF to amplify. 

### ISSUE THREAD

**Issue by idiom-bytes** [oceanprotocol/oceandao#184]
### Problem:
Right now, there is no "formal" pipeline for OceanDAO teams or otherwise to request others to #amplify their news.

By not formalizing this or putting it under an underlying Discord system (example: /amplify "message"), it limits our ability to operationalize this issue.

This also aligns with the following ticket:
Improve Signaling of Grantee Milestones - https://github.com/oceanprotocol/oceandao/issues/28

### Recommendation:
This problem I believe can be solved in 1 of 2 ways.
1. Create an #amplify channel. Participants that have won a grant, are able to request access & post here. Lower channel velocity to improve message quality (i.e. 1 post per 5 minutes). Posts here are basically high signal, and are consumed to be amplified by others.
2. Modify the existing #announcements channel. Same as above, but use what's already there. Would need to get verified with Monica/Casiana.

### DoD:
- [ ] New channel / workflow can be utilized by community.
- [ ] @OPF & @OceanDAO_, in addition to others (emphasis on the network), have an easier time curating news & asking for support.

**Comment by malvonme** [comment]
Great idea, we can do this now already, before the final comms plan stands. Let's do this. 

**Summary:**
- Create a closed/invite-only cannel in discord for grantees 
- Let them share important Twitter/Social announcements/updates
- OceanDAO comms touchpoint, potentially have it (re-)tweeted by official OceanDAO handle for more reach 
- Formalizing/Homing DAO Grantees' requests: https://docs.google.com/spreadsheets/d/11T4TT7Up90XJ_QQ2Ri1KltEoGXLJ6S-li06ieBJkiik/edit?resourcekey#gid=511721344

**Proposed naming:** 
DAO-Amplify 

**Home:** 
Discord/OPF/Channels/DAO-Amplify

**Proposed mode/specs by @Idiom, seconding this:** 
- Request invite only
- Slow Mode (5min)

**Next steps:**
I'd announce this channel some place where we can reach as many grantees as possible. 

**Questions:**
- Is there smth. like a "Grantee-Channel" in Discord? Smth. you get like auto-access to when receiving a grant? Else: Do this?
- How do I create an Invite-only Discord, @idiom-bytes ? Thx in advance

@trentmc @idiom-bytes, feel free to feedback/update if smth. should be diff.

**Comment by malvonme** [comment]
It's live, communicating it on Discord, Slack and Twitter rn:
https://discord.com/channels/612953348487905282/956906287923335229

**Comment by malvonme** [comment]
Channels shared in:

https://twitter.com/OceanDAO_/status/1507354880045953038?s=20&t=Z0S6gSDXeFoXIwxYhC7YvQ

https://discord.com/channels/612953348487905282/612953349003673629/956910229356953621

https://discord.com/channels/612953348487905282/776848812534398986/956909033460211722
