### ISSUE TITLE
#Port #UX Improvement: Bring One-Liner of a Proposal to the top for instant digestibility 

### ISSUE THREAD

**Issue by malvonme** [oceanprotocol/oceandao#187]
**Challenge:**
Sometimes it's hard to grasp / wrap your head around what a project does on a single glimpse. 

**Goal:** 
Allow voters to do their #DYOR on all propasals in one round in under 30 minutes. Instant graspability of proposals in port would help here.

**Proposed Solution:**
Move the Project One Liner section to the top of a proposal when displaying it. 

**Added:**
(We might want to keep the One-Liner where it is when CREATING proposals in the new portal though. Smtms it's easier to formulate a bang on one-liner when you already described the project.)

**DoD:**
- [x] Section PROJECT ONE LINER of Proposals are moved up in Port-Display, displayed right between PROJECT NAME and PROJECT DESCRIPTION
- [x] Rename from "Project One Liner" to "Project One-Liner" (right spelling according to Wikipedia)

![Bildschirmfoto 2022-03-24 um 15.10.57.png](https://images.zenhubusercontent.com/6230bfd994a5cba772c63765/691fede5-67e8-4e5e-8919-46de79c63ce0)

**Comment by idiom-bytes** [comment]
Thanks for the feedback Malte. :+1: 

I thought I had created a ticket for this in the portal already, but I did not.
https://github.com/oceanprotocol/oceandao-proposal-portal/issues

Me and Berkay spoke about updating this in the near future, and I agree. There are a few other improvements WRT to the discourse post coming from the Proposal Portal I'd like to see as well. :clinking_glasses:

**Comment by trizin** [comment]
https://github.com/oceanprotocol/oceandao-proposal-portal/pull/57

**Comment by malvonme** [comment]
New Order decided:

Project Name
Proposal One-Liner
Proposal Description
Project Description
Grant Deliverables
Value Add Criteria
Final Product

Core Team
Advisors
