### ISSUE TITLE
R16 - Recurring - Organize comms e-mail campaign for claiming grants

### ISSUE THREAD

**Issue by idiom-bytes** [oceanprotocol/oceandao#188]
### Problem:
2x projects did not claim a grant in R15. Both are good projects, and were expecting more from us.

### Toward a solution:
- Implement e-mail campaign + improve comms for claiming grants.
- Let's create a recurring task in [our ops script](https://github.com/oceanprotocol/DAOBot/tree/main/src/scripts/ops)
- Let's organize a batch e-mail that is shipped at the end of the round when funding takes place.

Criteria:
- K.I.S.S. Email campaigns are a magical dark hole.
- How did this get past current comms (Discord, Twitter, Documentation, Blog), Events, stewards, WGs? Where can we improve?
Creative - Perhaps just have a Funding Round Completion e-mail that includes: thank you for applying, and various targeted useful topics. Rather than just "how to claim", include "how to access higher funding tiers", "how to access shipyard".

Future: 
- Keep improving. Add a "So, you submitted your first Proposal." e-mail when a Propsal is submitted via portal.
- E-mail reminders. In-app alerts. Built into UX, claiming becomes unavoidable.

### DoD:
- [ ] In R16, after funding takes place, there should be an e-mail sent out to all winners, indicating to them how to claim a grant. 
- [ ] Update `script/ops` to include e-mail outcome, and any associated work

**Comment by malvonme** [comment]
Hi @KatunaNorbert, do we already use an E-Mail-Automation tool? Is it operateable for me or Terminal-Level?

I see three mails happening here:

1. Welcome (Trigger: Propsal submitted successfully, incl. acceptance from PGWG/Guide)

Hi there, thanks for submitting your porposal. Please keep these dates in mind:

- Voting starts on X. You might want to start communication on your proposal early, to reach the best possible audience
- The voting will end on Y. You might want to prepare a final call to action to get the last second voters interested
- (bold) If you win one of our grants, make sure to claim it in the course of 2 weeks maximum (till Z, date n time) after having been granted.

2. Mid of voting period (Trigger: half way into invoice-period for proposals per date)

Hey fellow DAOsailors,

we've reached the middle of the voting period. 
- Might be a good moment to do some communication / pr again. Get those votes! 
- Consider to use this landing page to funnel your follower base towards, to check out your proposal: OceanPearl/Applicant
- Please remember that you have 2 weeks to claim your grant here (ODAO_Website_Tools) before it closes!

3. After having won a grant (Trigger: Grant won)
- ConGRATulations! 🎉
- Make sure to collect your grant in 2 weeks time -> ODAO_Tools URL
- Tipp: by keeping the OceanDAO fam informed with updates/progress/deliverables, you increase your chances to win follow up grants -> hint #184 

--

Would like to iterate / refine wording once set up 🙌

**Comment by malvonme** [comment]
Related: 
https://app.zenhub.com/workspaces/oceandao-60a669231c2ed7000e90684b/issues/oceanprotocol/oceandao/166

**Comment by idiom-bytes** [comment]
@malvonme can we make sure that we have an email going out to people?
I would really like for us to be addressing ALL participants, not just winners.

Thank you!

**Comment by malvonme** [comment]
I wrote a template for this mail, adding a passage on top including all teams, not just winners:
---

SUBJECT: OceanDAO Round [Nr of CONCLUDED ROUND] - Participants Update

"Hi there, 

thank you for participating in the recent OceanDAO grants round!

In case you are one of the lucky winners: Congratulations on winning your OceanDAO grant!

If others received more votes than you this time, we highly encourage you to keep on building - and to apply again in the next round.

To all winners, don't forget to GO CLAIM YOUR GRANT:
https://oceanprotocol.com/web3Tools#ClaimGrant

DEADLINE:
April 25th, 2022, midnight UTC 
[FIXME - set to: AIRTABLE/FUNDING_ROUNDS/CURRENT_ROUND/FUNDING_DEADLINE]
(After this, we won't be able to fund your work with the granted amount.)

Further ways to benefit:
- Come say hi in our project guiding channel in our Discord (Find support, connections, feedback on your project, etc.)
- Join our Discord Channel (updates, clarify questions, join working groups, sync with ecosystem projects and Ocean core team members)
- Attend Town Halls (learn about the latest developments in OceanDAO, grantee updates, deep shares,..)
- Get vocal: (Share your updates in our Discord amplify channel, request to do a grantee update during Town Hall in ocean-dao channel, request a deep share,..)


Have a great day & enjoy the #BUIDL,
Your OceanDAO Team

**Comment by malvonme** [comment]
Would love to automate this with you @KatunaNorbert. I think a flat text automation should do for now, getting things automated quick. Mailchimp-tracking, etc, 2nd iteration. 

Will send mails to all participants out manually for this Round (16) to wrap up now, let's try to automate for Round 17.

Keeping this open for the automation part.

**Comment by malvonme** [comment]
**Sent out for Round 16 ☑️**

**### New DoD:**
- [ ] Automate template for Round 17ff, after Voting Ended and final calculations are up

**Comment by malvonme** [comment]
cc:
@KatunaNorbert

**Comment by idiom-bytes** [comment]
@malvonme Let's create a separate issue for automating this.

Until it happens, I am adding a repeatable task to our ops as described on the 2nd deliverable of this ticket so we can close this ticket.

**Comment by trizin** [comment]
It would be better to send a different email based on the status of the project rather than an "all in one" email @malvonme @idiom-bytes
