### ISSUE TITLE
OceanDAO - Staging Release #1 - 28/03/22

### ISSUE THREAD

**Issue by idiom-bytes** [oceanprotocol/oceandao#196]
### Release Overview:
We are working through the major deployments in staging, and making sure our system is working end-to-end. 

On the following slides, you can [find an outline of our timelines and workflow to test Seed Batch Grants](https://docs.google.com/presentation/d/18CL5YTJ2-WLQPwq755omqw1AF9ekW1DP_RHyf3V3IHw/edit#slide=id.g11f32ce5b4c_0_82).

For this release, our main workflows and tests have been done to validate the following features:
- Creating a Project.
- Creating a Proposal.
- Applying for Core-Tech earmark
- Completing a Proposal
- Delegating Votes
- Voting Scores
- Reviewing Winners
- Reviewing Funding Distribution

We have written new tests, validations, and improved the UX with validations. Many tests were also done via the User and Admin Dashboards. Whenever possible we also included OceanDAO participants to verify our updates. Our goal is to continue increasing the number of participants, tests, and coverage we provide.

**Migration Includes**
Work done to make proposal portal usable by OceanDAO participants.
- Importing records from Airtable => Proposal Portal DB
- Updating Admin 0x for projects => Airtable & Proposal Portal DB

**Important Dates:**
As communicated, here were the following dates for this release cycle.
- Deadlines - 22nd - Make sure everything is merged into staging and deployed to vm
- Deadlines - 24th - We're starting voting
- Deadlines - 28th - We're completing voting

For a more detailed overview of our schedule, [please view our Roadmap and Staging Ops](https://docs.google.com/presentation/d/18CL5YTJ2-WLQPwq755omqw1AF9ekW1DP_RHyf3V3IHw/edit#slide=id.g11f32ce5b4c_0_82).

### DoD:
Feature Testing & Validation:
- [x] Snapshot - Validate that delegates are working and can be boosted. (everyone)
Ongoing - [ ] Website - Voting Power Dashboard (everyone)
- [x] Website - Validating wallet connect (everyone) => Ask previous user to help test 
- [x] Proposal Portal - Import/Sync script from Airtable (dev only)
- [x] Proposal Portal - Admin Portal - Completing & Reviewing Proposals (admins only)
- [x] Proposal Portal - Admin Portal - Accepting Core-Tech Earmark (admins only)
- [x] Proposal Portal - Admin Portal - How to add administrators to the Portal (dev only)
- [x] [Max Funding is limited to 20k](https://github.com/oceanprotocol/DAOBot/pull/154) (everyone @ Proposal Creation & End Voting)
- [x] Proposal Portal - Min Funding - Implement minimum amount requested & update distribution calculations to take this into consideration. Projects who did not meet minimum requested funding should be removed in a fair way.

UX Testing & Validation:
- [x] As an existing user, I am able to login with the wallet I submitted and created a proposal for R16.
- [x] As an existing user, I am able to manage my proposal and have all the expected information show up inside of Port.
- [x] As a new/existing user, I am able to create a project setup all required information, submit a proposal, and apply for a Core-Tech Earmark. The UX/UI lets me know what I need to do to complete this, and Admins are able to take the user through to completion.
- [x] Ongoing - As a new/existing user, I am able to submit completion requests, understand they were accepted, and that I am able to submit another proposal.

Backend:
- [x] Various improvements around managing requests, and validating that users are not hammering the server, or doing any funny business. Updates were made to properly clear the checks, and we are continuing to provide support around issues relating to multiple requests.

**Comment by idiom-bytes** [comment]
This is a running list of issues that came up, features that were discussed or tested, and major outcomes wherever possible. Every actionable as a result has been dealt with (but not necessarily completed).

**[Document Known Issues]**
:heavy_check_mark: - [500 OCEAN check is not done on FE](https://github.com/oceanprotocol/oceandao-proposal-portal/issues/31)
:heavy_check_mark: - [Proposal Standing checks](https://github.com/oceanprotocol/oceandao-proposal-portal/issues/41) are not done on the FE

**[Feature - QF Distribution Review]**
Task: Communicate & gather feedback.
:heavy_check_mark: Done: Berkay has provided links to sample QF distributions that played out based on various designs. I have [prepared a comms around it](https://discord.com/channels/612953348487905282/908016760190537798/957382138624360468), so we can have the Params+Roadmap WG review & provide feedback.

**[Feature - Admin Portal & Completing Proposals]**
Task: Get admin portal up and running.
:heavy_check_mark: Done: Most of the work has been done. The import/sync script has also been deployed on staging and verified.

**[Feature - Migrate DAOBot into Portal]**
Task: Discussions around migrating DAOBot scripts into portal. [Not the highest priority](https://github.com/oceanprotocol/oceandao/issues/183). We can keep airtable around for the next while. No task or actionable.
:heavy_check_mark: Done: Created task. Move on.

**[Feature - Website Delegation Review]**
Task: Website updates for delegation portal could use more usage & feedback.
:heavy_check_mark: Done: We have continue to increase visibility around testing and staging environment. We have also asked Robin and others to increase testing around it.

**Comment by w1kke** [comment]
I can see the delegates but there is an error - the Ocean Marketplace tokens are not taken into consideration by the page.
Everything else looks to be working - e.g. tokens on Polygon

**Comment by idiom-bytes** [comment]
The latest release was verified once again, and deployed to production.
- All proposals have been migrated to production portal
- All critical features have been tested and reviewed inside portal
- We believe at this point, most mission-critical updates have been released.
- There are a couple of small issues for us to still address (see comments from @w1kke above)

Remaining:
- We still have tickets open to submit additional UX/UI updates for R16. We will be prioritizing these to complete the remainder of the work.
- We decided to defer QF to R17 as originally planned. Although most of it was implemented, participants had previously declared the DAO is changing fast. Below you can find the items associated with that.

Deferred - QF:
- [ ] DAOBot - QF Calculations were working and verified, however were reverted until R17.
- [ ] Pearl needs to update their FE/Leaderboard in order to reflect changes with QF.

**Comment by idiom-bytes** [comment]
Additional PRs in pipeline for this release:
https://github.com/oceanprotocol/oceandao-proposal-portal/pull/73
https://github.com/oceanprotocol/oceandao-proposal-portal/pull/74
https://github.com/oceanprotocol/oceandao-proposal-portal/pull/75
https://github.com/oceanprotocol/oceandao-proposal-portal/pull/77
https://github.com/oceanprotocol/DAOBot/issues/166

**Comment by idiom-bytes** [comment]
We have completed this, versioned our releases, and are now resuming our staging branches.
