### ISSUE TITLE
Relax "500 OCEAN in wallet" for existing grant receivers

### ISSUE THREAD

**Issue by TimDaub** [oceanprotocol/oceandao#2]
- rugpullindex.com [received a grant in round 2](https://port.oceanprotocol.com/t/oceandao-r2-proposal-rugpullindex-com/364); It fulfilled the "[Criterion (3). Minimum Proposal Requirement.](https://github.com/oceanprotocol/oceandao/wiki/project-criteria#details-of-criteria)".
- For each grant proposal, a minimum of 500 OCEAN is required in a grantee's wallet. The argument is that "this helps to filter towards people with a vested interest or “skin in the game” in OCEAN - that is, Ocean community members. Ocean Protocol team members will verify."
- rugpullindex.com is applying in round 3 too but doesn't have 500 OCEANs in their wallet at the time of writing; IMO I've made it sufficiently clear that rugpullindex.com has a "vested interest" in OCEAN.
  - I've already received a grant in the past
  - I have committed to work for the community in the future
  - I've "hardcoded" OCEAN-related constants into rugpullindex.com
  - OCEAN and rugpullindex.com share some of their user base

## Change proposal to the criterion

- For a new project, ask for 500 OCEANs in their wallet as a filter towards people with a vested interest in OCEAN
- For projects that already received a funding round, do NOT require 500 OCEAN in a wallet as vested interest is assumed naturally

**Comment by w1kke** [comment]
I can borrow you 500 $OCEAN if you need them. Ping me on Telegram.

**Comment by TimDaub** [comment]
Hey @w1kke, thanks that's noble of you. My problem isn't getting ahold of 500 OCEANs. I have them. I just saw my situation as an opportunity for improving OceanDAO's process.

**Comment by w1kke** [comment]
Ok, I misunderstood that.

In case of automating the process in a smart contract this would mean that the DAO has to keep a list of all previous grant recipients while the 500 $OCEAN in the wallet of a proposer would be a check of that wallet. We are not there yet so @anapheys will then keep track of that list.
So from that point of view I would stick to the current solution as it scales better but that is just my 2 sats.

**Comment by TimDaub** [comment]
Thanks for clarifying. I wasn't aware that the DAO indeed checks for the existence of 500 OCEAN. I thought the change may just entail changing the Wiki's markdown file. I'll make sure to send 500 OCEANs to my wallet then.

And, if you don't mind, I'll leave the issue open for improvements later down the road.

**Comment by anapheys** [comment]
Thanks for working together on this. The 500 Ocean is to ensure "skin in the game" for potential grant recipients.
