### ISSUE TITLE
Pack voting time into the week

### ISSUE THREAD

**Issue by TimDaub** [oceanprotocol/oceandao#20]
Of course, I can only speak for myself here but I found the last five days very intense. Campaign is hard. 

If I remember correctly, the R8 vote didn't go through Monday night CEST Berlin time but instead ended usually on Monday afternoon Berlin time.

I like that e.g. the due diligence phase always starts on Tuesday: but since the introduction of the two-day due diligence period, it meant that the votes usually go through the weekend. I don't know about others, but it doesn't contribute to a better work-life balance/harmony on my end.

I'd prefer to conduct all voting-related activity into a time block "during the week". E.g. due diligence deadline starts sometime every first Monday of the month, is shortened to 1 day and then voting takes place until e.g. Friday afternoon.

**Comment by trentmc** [comment]
Specific voting time has many factors. Current setup has been optimized over the last year based on these factors. Closing this issue.
