### ISSUE TITLE
[Community] Outbound & Inbound Processes for scalable Community Outreach

### ISSUE THREAD

**Issue by idiom-bytes** [oceanprotocol/oceandao#21]
I would like for us to consider increasing messaging across all channels.

[Problem]
- We are engaging granularly, in non-scalable ways.
- We are hosting events and spending cycles on outreach, without leveraging our channels effectively.
- We do not have well defined processes that enables this outreach to be scalable.

[Goal]
- Increase engagement with all ocean communities/holders.
- Define processes that enables us to scale our engagement across all communities.

[Towards a solution - Inbound vs. Outbound]
Outbound: If we're doing 1-1 answers, we should engage participants where they are at.
Inbound: If we're hosting an event, AMA, or a group session, we should invite people across all channels (inbound)
Community Managers: Create a list of all community managers, so stewards are well known.
Processes: Define processes for hosting events & increasing engagement across all communities. 

[Community List]
- Discord
- TG Official
- TG Unofficial
- Twitter

??? Do we have a presence here? Who does the community management?
- Reddit
- TikTok
- Hacker News

[How - Example]
"AMA between Robin & Governauts, for the TG Unofficial"
- However, when doing so... Let's engage all communities described above, so we can always be increasing visibility.
- I would like to formalize/process/automate this a bit so we can make it repeatable/low overhead to manage.
- Events [can be registered inside of our DAO calendar](https://calendar.google.com/calendar/u/1?cid=Y19uZ2xraDlzOTVqOGxzcjBwOWg5ZnAwczBvc0Bncm91cC5jYWxlbmRhci5nb29nbGUuY29t)
- Community managers could help make sure that events are propagated correctly.
- Events could be announced in one of the Discord channels w/ community managers tagged, so they can help share & promote events into the local community level.

**Comment by idiom-bytes** [comment]
Conversations between TEC & OceanDAO WRT - Working Groups (WG) and their structure.

From Idiom:
> Hi @Tam2140 , I'm basically trying to reach out to the community management hivemind for better processes.
> Basically, I believe we have a lot of room for improvement WRT how we organize ourselves as a DAO, and channels for outreach.
> 
> Example:
> A team in the DAO wants to host an AMA.
> - How would you have it scheduled?
> - How would you have it communicated via all appropriate channels?
> 
> I have been following a bit more about what's going on at TEC and really appreciate all the amazing work that has been established around community & outreach.
> 
> I was wondering if you might be able to share a little a bit about some tools and workflows to improve coordination & efficiency around this.
> Is there a way for me to look behind your community management curtains?
> 
> Thank you!

From Tam:
> The great news is that there is no curtain. One of the core tenets of the TEC, in fact also the name of one of our working groups, is transparency. All of our calls are open to anyone to join and all of our calls are recorded and available on our youtube channel. https://www.youtube.com/c/TokenEngineeringCommons
> 
> There are 4 working groups that I would like to put on your radar.
> Stewards
> Communitas
> Soft gov & culture
> Gravity.
> 
> Let me explain why. 
> 
> The Stewards WG is where have a transversal perspective of everything happening in every WG. This is where we, as Stewards or WG leads, coordinate and problem solve collectively. We have a weekly sync, a bi-weekly discussion group (we call Council), and Scrum events like Sprint Planning, Sprint Retrospective and weekly Sprint Reviews (aka our Community call where each WG presents their completed work that week).
> 
> The Communitas WG is the group focus on community building, onboarding and token holder relations. This group is comprised of former group initiatives like Hatcher Outreach (a archived WG) and Orientation (which is an initiative that was incubated under Soft Gov).
> 
> Soft Gov & Culture is the WG responsible for crafting and disseminating our culture which, as you might already be aware, have Elinor Ostrom's 8 principles for Commons deeply woven in.
> 
> Gravity is the WG that is responsible for transforming conflict in our community. There is a process they have defined to mediate conflict as well as training they provide to the entire community in mediation and NVC, among other topics. These trainings are currently happening on Tuesdays.
> I would be happy to hop on a call with you if you want to dig into anything specifically and I invite you to look at our calendar and join any of the above meetings that speak to you. https://calendar.google.com/calendar/u/1?cid=NW1rZXAxYWQxajg2MGs2ZzdpN2ZyOHBscTBAZ3JvdXAuY2FsZW5kYXIuZ29vZ2xlLmNvbQ

**Comment by trentmc** [comment]
Outreach to increase # proposals is now in good shape, since $ requested >> $ available for a given round. Can close this issue
