### ISSUE TITLE
Review Q&A from R16 and proposal portal. Gather information and update wiki with useful information.

### ISSUE THREAD

**Issue by idiom-bytes** [oceanprotocol/oceandao#215]
### Problem:
There were many Q&A around R16, portal, proposals, etc... that are getting answered but not getting rolled back into our documentation.

Let's gather up these major points as we ship R16 out the door, and update our wiki with them to make it easier for participants to navigate the portal in future rounds.

## DoD:
- [ ] Wiki has been updated with various FAQ and a guide, to use the proposal portal.

**Comment by malvonme** [comment]
- Can I submit a new Proposal before having closed (sent deliverables) the old one?
- Can I write a proposal with a new / different wallet address:
https://discord.com/channels/612953348487905282/776848812534398986/958819048248979466

**Comment by trentmc** [comment]
obsolete
