### ISSUE TITLE
Proposal Portal: Core Tech Earmark Select

### ISSUE THREAD

**Issue by malvonme** [oceanprotocol/oceandao#216]
### **Challenge:**
Applicants tend to mark their project as core tech earmark candidate, without always following the recommended steps to do so, here:
https://github.com/oceanprotocol/oceandao/wiki/OceanDAO-Tech-Earmarks

### Recommendation:
When writing a new proposal and Earmark: Core Tech is selected, we could display a note/hint to seek approval in:
https://discord.com/channels/612953348487905282/908016816029319178
as discribed in the docu above, before submitting the proposal with "earmark core tech".

**### DoD:**

- [ ] Applicant understands s*he shall seek approval for the earmark core tech before submitting the proposal
- [ ] Applicant can click the link to the docu detailing the process: https://github.com/oceanprotocol/oceandao/wiki/OceanDAO-Tech-Earmarks

**Comment by idiom-bytes** [comment]
I think this is a bug on the FE. A lot of people experienced this. Let's fix this.

**Comment by malvonme** [comment]
Any update on this front or seeking sparing / chat about it @KatunaNorbert? If you want, ping/tag me! 🫶

**Comment by malvonme** [comment]
I think we id'ed it as a bug. @KatunaNorbert, you're onto this. Perfect. As I trust your UX-eye 150%, I will un-assign me. Thanks for taking this on!
