### ISSUE TITLE
More to come.

### ISSUE THREAD

**Issue by idiom-bytes** [oceanprotocol/oceandao#22]
------------

**Comment by trentmc** [comment]
**On terminology.** From @idiom-bytes in slack:

> I would recommend us using nomenclature from TEC until we further refine/theme this within Ocean Protocol ecosystem.
> Group - A squad, team, dao, group of people with a well-defined mission.
> Steward - The owner(s) of this group.
> Members - Everyone within the group.
> This will help me further define groups & TH structure/comms.

I am fine with this. It's one less thing to have to invent, and will help bridge comms between OceanDAO and TEC.
