### ISSUE TITLE
Contract or UX bug: False Voting Power Calculation

### ISSUE THREAD

**Issue by malvonme** [oceanprotocol/oceandao#220]
### **Challenge:**
Though 10k+ $OCEAN are held on a metamask wallet, only 109 $OCEAN in voting power are calculated. 

### **Recommendation:**
Find root cause and update UX or documentations for others to resolve this quick. 

### **DoD:**
- [x] Voting Power is calculated right / true to wallet Ocean holdings
- [x] Update UX / UI if necessary and possible (Snapshot premise)

**Comment by idiom-bytes** [comment]
Can you provide the address?

**Comment by malvonme** [comment]
Sure: 
0x4e1C5fD0C198Bcd7689Ec701  DdcE1E4b3804fFd3
(with spacer in between re: crawl)

Or simply:
crypto  wally.eth
(same)

@idiom-bytes 

Thx!

**Comment by trizin** [comment]
@malvonme Could you check if it's displaying the correct voting power now?

**Comment by malvonme** [comment]
Checked it and it seems to work now (at least in staging https://demo.snapshot.org/#/officialoceandao.eth/proposal/QmV3z4HTmqiEBU7upjwWVQi93aFBmM8B4KwCRfiXnQyvxV)

Thx @trizin !! 🙏![Bildschirmfoto 2022-05-02 um 16.10.13.png](https://images.zenhubusercontent.com/6230bfd994a5cba772c63765/3c57bd73-c958-4ee1-8d93-9cefff3a0158)
