### ISSUE TITLE
CDN/DNS Issues - Bunny.cdn & https://vote.oceanprotocol.com/#/

### ISSUE THREAD

**Issue by idiom-bytes** [oceanprotocol/oceandao#222]
We seem to be having a CDN/DNS issue.

More on Discord.
![Screenshot from 2022-04-11 11-38-13](https://user-images.githubusercontent.com/69865342/162807315-540462a7-3e76-4318-bee3-68b15ac0530d.png)

**Comment by trentmc** [comment]
Done
