### ISSUE TITLE
Improve Documentation/Comms around "Min USD Requested"

### ISSUE THREAD

**Issue by idiom-bytes** [oceanprotocol/oceandao#223]
### Problem:
Lots of participants are not understanding this field, in their proposal submission application.
I have created the same ticket inside of portal to improve UX/UI
https://github.com/oceanprotocol/oceandao-proposal-portal/issues/115

3/4 Projects would have rejected their funding.
![Screenshot from 2022-04-11 19-16-49](https://user-images.githubusercontent.com/69865342/162865943-daa2a9ba-cb1f-47b4-a412-1175d40d8c1b.png)

We need to improve Comms/Intuition around this.

## DoD:

- [ ] - Communicate this via e-mail to participants
- [x] - Improve explanation of this on the wiki
- [x] - Update our old Proposal Template wiki page, with a "How To: Submit a Proposal on

 Seed".

**Comment by w1kke** [comment]
I remember the discussion about this in the Parameters working group - I think another iteration is needed in that group.

From my point of view we wanted to introduce this to make sure there is not so much "change" of tokens attributed to projects that will not be collected or is not enough to reach any goals. But this adds a lot of complexity.

Alternatively we could set this to 500$ or a similar value automatically - if the project gets less than that from QF it will not get anything and the tokens can automatically be distributed to other projects in the round. So more like a global Min USD Requested value. This will then also remove the need to set and understand this while still serving the purpose.

I am always in favour of adding "expert modes" to UIs - so this parameter could then also be moved there for more advanced users and to keep the general UX flow as simple as possible.

**Comment by idiom-bytes** [comment]
@w1kke checkout this task
https://github.com/oceanprotocol/oceandao-proposal-portal/issues/115

We followed a similar implementation as what you recommended.
We set the default to zero for now.
Fees may be sufficient for others to not want to claim.

Let's have you try it out when we ship it, and get your feedback.

**Comment by malvonme** [comment]
![Bildschirmfoto 2022-04-19 um 15.14.31.png](https://images.zenhubusercontent.com/6230bfd994a5cba772c63765/a2b822de-3a7f-4add-bed5-58e8feaa26ae)Updated Wiki with "Min USD Requested" feature hint/highlight:
https://github.com/oceanprotocol/oceandao/wiki#steps-for-projects

**Comment by malvonme** [comment]
Updated the How To: Submit a Proposal on Seed page in wiki:
https://github.com/oceanprotocol/oceandao/wiki/Write-Proposal

CC: @idiom-bytes
