### ISSUE TITLE
[DAO] Update voting guide to reflect Quadratic Voting implementation

### ISSUE THREAD

**Issue by dcrapis** [oceanprotocol/oceandao#23]
Problem
The voting guide in `Voting.md` is outdated.

Solution
Update voting guide to reflect changes to the new voting process starting on R11.

Process
I'm updating the [voting guide](https://github.com/dcrapis/oceandao-wiki/blob/master/Voting.md) in my repo following the process described [here](https://stackoverflow.com/questions/10642928/how-to-pull-request-a-wiki-page-on-github#11481887). I'll request review/merge when ready.

**Comment by idiom-bytes** [comment]
Hi @dcrapis, I have taken your + Angela's update and integrated it into the wiki.

https://github.com/oceanprotocol/oceandao/wiki/Voting

**Comment by idiom-bytes** [comment]
Hi @dcrapis, I believe this ticket is concluded and am closing it.
