### ISSUE TITLE
R17 - Implement 2nd/3rd Grant Earmark

### ISSUE THREAD

**Issue by idiom-bytes** [oceanprotocol/oceandao#247]
There is a new Earmark and configuration for R17 that needs to be implemented for 2nd and 3rd time applicants/proposals.

### DoD:
- [x] Roberto: New earmark is implemented inside of airtable. 
- [x] Trizin: New earmark is implemented inside of portal backend
https://github.com/oceanprotocol/oceandao/issues/249
- [ ] Norbert: New earmark is implemented inside of portal frontend
https://github.com/oceanprotocol/oceandao-proposal-portal/issues/132
- [ ] Roberto/Trizin/Norbert: New earmark is implemented inside of daobot
Norbert - [ ] New Notion view + R17 Notion page needs to be updated to reflect this view
Malte - [x] Documentation in Wiki needs to be updated

https://docs.google.com/document/d/1CGqLJgWKwzDlZFgA7FPmkyRaZHmorutMv-GaSroMSPw/edit?usp=sharing.

**Comment by malvonme** [comment]
Wiki is updated:
https://github.com/oceanprotocol/oceandao/wiki#earmark-categories

**Comment by malvonme** [comment]
I also updated the wiki for the Round 17 date-specs:https://github.com/oceanprotocol/oceandao/wiki#oceandao-round-17

If not in, let's maybe put this into the "Round 17 kickoff" Ticket? Maybe with the Blog? 

![Bildschirmfoto 2022-04-19 um 14.51.21.png](https://images.zenhubusercontent.com/6230bfd994a5cba772c63765/432df4b0-e397-4a8f-9a59-bbbfdb924c86)cc @idiom-bytes 

EDIT - Resolved, added to this recurring ticket:
https://app.zenhub.com/workspaces/oceandao-60a669231c2ed7000e90684b/issues/oceanprotocol/oceandao/238

**Comment by KatunaNorbert** [comment]
Shouldn't we also update the Funding Tiers section?
![Screenshot 2022-04-20 at 10.36.11.png](https://images.zenhubusercontent.com/5ff449b376fe2511ba59495d/ff254280-20e4-498f-80d3-570fa77bf944)

**Comment by malvonme** [comment]
Thx for the hint @KatunaNorbert!

I think you mean Experienced Project -> 3 or more grants, right?

As @idiom-bytes stated in the last parameters call that we should limit 2nd/3rd Earmarkers to 10k. 

Earmarks, on return, probably shouldn't be in there, as they have their own section. 

If you had a different idea, could you elaborate?

Thx!

**Comment by idiom-bytes** [comment]
15,000 OCEAN for 1st Time Teams (non-outreach category)
9,000 OCEAN for 1st Time Teams (outreach category)
35,000 OCEAN for 2nd/3rd Time Teams
26,000 OCEAN for Core Tech Initiatives
115,000 OCEAN for remaining General Grants

**Comment by malvonme** [comment]
Ok, I see, so make this the earmarks instead of the caps. 

This will take some minutes, made it a new task:
https://app.zenhub.com/workspaces/oceandao-60a669231c2ed7000e90684b/issues/oceanprotocol/oceandao/251
