### ISSUE TITLE
[DAOBot] Implement `sh dump_gsheets_vote_history.js` to dump basic schema to analyze voter history.

### ISSUE THREAD

**Issue by idiom-bytes** [oceanprotocol/oceandao#25]
#### Proposal:
> Implement the same schema output as V0.1 of what TEC will output from their python script.
> This "TEC DAO Schema output" would be valuable to have inside of DAOBot, however this is currently not directly in our roadmap.
> Octopus is delivering this in python. I believe someone should consolidate current functionality inside of daobot (i.e. this could be fed into a Discord/TG bot.) 
> Can someone deliver this against the `github/daobot/` repo, so we can dump this into the gsheets file that we use?

[Status Quo / Problem]
I don't believe the granular data inside, 150 gsheets in .xlsx format is valuable...
**The granular gsheets voting functionality, should either be deprecated, or evolve.**

[Towards a solution]
- Having this cleaned and structured into a schema that can be output by daobot...
sh dump_gsheets_vote_history.js 2>&1 (the exact work you are doing by python) is definitely useful.
- Anyone can download the data and analyze it. It matches TEC's standards.

#### Background

A conversation between [🐙 octopus] and [Idiom] prompted the discussion of gathering data from Snapshot, in a format that generates data/schema that serves a good structure for analysis.

> Idiom: However, this information is setup like:
> [IPFSHash.csv]
> address, choice, votes
> it may be more useful to.... have.... 1 csv file with
> round #, ipfshash, address, choice, votes. 
> is there a file format/schema/structure that would make it easier for you consume this data?
> 
> Octopus: I think the optimal would be these columns:
> "Round", "Address", "ProjectID", "Choice", "Balance", Timestamp
>  

This functionality currently sits outside of our roadmap/priority, although a lot of the work is already completed. We have stopped dumping granular data to sheets inside of [OceanDAOVotes](https://docs.google.com/spreadsheets/d/1e4xb6m-aKcBhwob_p7ereSFneXFPpDjUbSjz13smmHI/edit#gid=1767052349) because it's not being consumed by anything.

However, the functionality is still used under the hood, to map/reduce/summarize vote metrics from the ballot/voting period. Octopus is currently implementing this in python, however our current solution is not too far from this.

[Use Cases]
- I had a chat inside of Governauts about this, WRT who is doing the best snapshot analytics: unique wallet|voter power growth, voter behaviors, ballot types, voter retention, etc....?
- I believe this data should be available via DAOBot, as a way to conclude the current export implementation.

[Considerations/Intuitions]
- Although it's not directly on our roadmap, as this work is already being done (although on python), would be a great way to provide this via DAOBot.
- Further reasoning to this, is there is a lot of work already done around this. The current implementation should either be deprecated or improved.

#### DoD
- [ ] Output 1 sheet that has all historical summary in a format that is easy to consume & process
> "Round", "Address", "ProjectID", "Choice1", "Choice2", "Choice3", "Balance", Timestamp

**Comment by trentmc** [comment]
Super low priority, closing
