### ISSUE TITLE
IDEA for AUTOMATION: R17 (recurring) - Create Discord events

### ISSUE THREAD

**Issue by malvonme** [oceanprotocol/oceandao#252]
### **Goal:**
We want to have all upcoming events of the week as EVENTS in discord (compare: screenshots). 

Ideally, a few days in advance for ppl to be able to plan up front / factor it into next weeks personal Cal. Let's say: every Friday latest, events for upcoming week.

It's still manual for now, event creation, but let's keep an eye on automation down the road. 

### **Benefits:**
- Visibility of our Events
- Deeplinks to invite friends or for us to do Comms with

**### DoD:**
- [ ] You have Admin-Rights in Discord
- [ ] You created all events for the upcoming week (WG calls + Town Hall)
- [ ]  It's Friday latest, next weeks events are up. Have a ☀️ Weekend!

---
### **Text Templates per Working Group / Town Hall:**
(Use your local time, Discord Events will adapt accordingly. Display here in UTC for reference)

**OceanDAO Parameters & Roadmap WG**
2pm UTC Every other Tuesday
In this weekly open discord voice we discuss future roadmap items and parameters of the OceanDAO, like earmarks, quadratic funding, balance of power, sibling-attack-protection, etc..

**OceanDAO Engineering WG**
3pm UTC Tuesday
Every week do an OceanDAO Engineering Team sync (core and contributors) in an open discord voice session right here. Learn about the latest BUIDL in OceanDAO Land. 

**OceanDAO Core Tech WG**
2pm UTC Wednesday
The Core Tech Working Group is directed towards high-impact technical outcomes, including identifying high-priority tech projects (e.g. earmarks), find teams to work on them, and help shepherd those projects to completion.

This voice is weekly and open. If you are interested, feel free to join and contribute to this 

**OceanDAO Town Hall**  
3pm UTC Wednesday
Learn about all the latest news and updates in OceanDAO land, including Working Groups, Grantees, new features and budget allocation. 

It's weekly and open for everyone to tune in, learn and discuss all things OceanDAO.   

**OceanDAO Project Guiding WG**
3pm UTC Wednesday
If you are your OceanDAO Grant Proposal right now and have open questions, jump on this weekly open voice and connect to experienced project guides.   

Just as much: if you wrote proposals in the past or are an expert in one of our verticals (Data, Blockchain/AI, Outreach, etc.), we love you to join here and start helping new applicants. 

  **OceanDAO Outreach WG**
2pm UTC Thursday
In here, we discuss outreach initiatives to build, educate and bring together the Ocean Protocol Ecosystem participants - on a bi-weekly basis. DAO-funded outreach initiatives snc with our ambassadors, comms core team members and trusted community content contributors.

![Bildschirmfoto 2022-04-21 um 14.54.27.png](https://images.zenhubusercontent.com/6230bfd994a5cba772c63765/d2283ba0-bc3b-4ba8-b2ce-567af9fd849d)

![Bildschirmfoto 2022-04-21 um 14.54.39.png](https://images.zenhubusercontent.com/6230bfd994a5cba772c63765/58fadb26-c524-4bac-bc61-93cfb1ef5cf3)

**Comment by malvonme** [comment]
Hey @idiom-bytes, could you put this ticket into the JSON and automate it? Recurring each week? Thx! 🙌

**Comment by malvonme** [comment]
Update:
Outreach WG is weekly now. Ambassadors and MarComs asked for this. Was agreed upon as great idea. Can be churned back to be-weekly if not needed.

**Comment by idiom-bytes** [comment]
Added to ops schedule. I broke this down into 2 tasks, each one representative of the First (1) & Last (2) Sprint that we compete each funding round.

**Comment by malvonme** [comment]
Perfect, thx @idiom-bytes  

I have a minor update for the events per week:
Parameters Working Group has been shifted towards bi-weekly, from weekly. 

I updated the initial list above to not spam 👆

**Comment by idiom-bytes** [comment]
This is now scripted and tasks are generated automatically.

I think this task is now completed.
Please find both tasks for R18 below, and move this to closed.
https://github.com/oceanprotocol/oceandao/issues/381
https://github.com/oceanprotocol/oceandao/issues/383

Thank you!
