### ISSUE TITLE
Minor Port/Discourse Improvement:

### ISSUE THREAD

**Issue by malvonme** [oceanprotocol/oceandao#253]
**### Goal:**
I want to improve DYOR UX on Port.Oceanprotocol.com with a little tweak:

When researching Port entrys/projects, every click on a link FORWARDS to the target page. 

I leave Port, no open tab.

Could we instead make it so that every click on a link/outlink opens a new tab?

Far better/easier and expected behavior while DYOR. 

Example:
https://port.oceanprotocol.com/t/grant-proposal-homomorphic-encryption-for-ocean-market/816

**### DoD:**
- [ ] every click on a link/outlink opens a new tab

**Comment by idiom-bytes** [comment]
Dug into this, I believe this is a personal setting inside of Discourse.
I do not believe that this can be applied to all proposals/users by default.

![Screenshot from 2022-05-04 22-38-27.png](https://images.zenhubusercontent.com/601eeb154030993736fc619e/8c20e52a-4f51-4d27-9f32-acb5c7dc60a6)

Please give it a whirl, and close the ticket.
We can then link users back to this issue so they can self-serve.

Thank you!

**Comment by malvonme** [comment]
Big help, thank you for taking the time @idiom-bytes 

#closed
