### ISSUE TITLE
[Write Blog Post OceanDAO]: New Round 17 features

### ISSUE THREAD

**Issue by malvonme** [oceanprotocol/oceandao#260]
**### Goal:**
Have everyone easily understand the updates we make to Round 17 for a more efficient and even distribution of funds, including: 

- Quadratic Funding
- Min USD Funding
- $20k Ceiling
- New Earmark 2nd/3rd Time Entrants

### **DoD:**
- [ ] Write blog post about new features above
- [ ]  Not longer than 5min read
- [ ] Submit to Main Medium for checkup

**Comment by idiom-bytes** [comment]
I believe this is completed, no?

**Comment by malvonme** [comment]
No... this was not about the general R17 kick-off medium, but an idea on explaining briefly the updates we have for Voting Round 17. Given latest updates / focus churn, I would still close this for now, yes. 

Cheers
