### ISSUE TITLE
[DAO] Update voting guide to reflect Batch & Weighted Ballot Voting implementation 

### ISSUE THREAD

**Issue by idiom-bytes** [oceanprotocol/oceandao#27]
Problem
The voting guide in Voting.md is outdated inside of the wiki
https://github.com/dcrapis/oceandao-wiki/blob/master/Voting.md

Solution
Update voting guide to reflect changes to Batched + Weighted Ballot process starting on R11.

Process
- [ ] Updating the voting guide in your own repo following the process described here.
- [ ] Provide a request/review/merge when ready.

**Comment by idiom-bytes** [comment]
@dcrapis, is this something that you'd be able to help with?

**Comment by dcrapis** [comment]
@idiom-bytes yes i can get to this later this week.

**Comment by idiom-bytes** [comment]
Incredible, thanks @dcrapis!

**Comment by dcrapis** [comment]
@idiom-bytes the voting guide is fully updated with the single-ballot weighted voting description/resources here:
- https://github.com/dcrapis/oceandao-wiki/blob/master/Voting.md

Can you please review and then merge if it looks good?

**Comment by idiom-bytes** [comment]
That looks awesome @dcrapis! Thank you for the contribution!

I have merged the update into [OceanDAO's Wiki - Voting](https://github.com/oceanprotocol/oceandao/wiki/Voting)!
Please feel free to close the issue!

**Comment by idiom-bytes** [comment]
I guess I might have to close the issue.
Thank you again @dcrapis!
