### ISSUE TITLE
Product Comms/Documentation: Improve Portal Documentation towards social layer

### ISSUE THREAD

**Issue by malvonme** [oceanprotocol/oceandao#273]
**### Goal:** 
Improve wording of first draft of "How to write a proposal in our new Portal" towards a more human, more welcoming language. 

**### DoD:**
- [x] Everyone, even no-coders, understand how to write a proposal
- [x] Say Hi and Bye to be more welcoming
- [x] Give hot tipps and prevent noob mistakes (like no 500 OCEAN in wallet)
- [x] Ad Navi-Helper "back to mother page", comp.: Town Hall Page
- [x] Be as short as possible

Documentation:
https://github.com/oceanprotocol/oceandao/wiki/Write-Proposal

**Comment by malvonme** [comment]
Updated the documentation: 
https://github.com/oceanprotocol/oceandao/wiki/Write-Proposal

Communicated it via Social Channel: 
https://twitter.com/OceanDAO_/status/1521170006775640064?s=20&t=IRKZgm-jur5kquR9ekki_w

**Comment by idiom-bytes** [comment]
I've also done a first pass at the proposal portal to update the How-To
https://github.com/oceanprotocol/oceandao-proposal-portal

I propose we close this ticket.
Let's make sure that we keep rolling back documentation and how-to's into: tasks + documentation

Cheers!
