### ISSUE TITLE
Ocean Protocol Ambassadors Program (OPAP) - Change of Management affecting submission (effectively appearing as a new project)

### ISSUE THREAD

**Issue by zippy1979** [oceanprotocol/oceandao#274]
### **Challenge:** 
The new submission has been done by Upkar not Robin so the system does not recognise the connected wallet as an "experienced" project.

### **Goal:** 
To change the Proposal funding amount from $3k to $20k and remove the earmark protection. Also to resolve this as a bug for future teams in a similar situation. 

### **Definition of Done (DoD):** 
- [ ] Funding requested is $20k 
- [ ] "New Outreach" earmark eligibility removed

CC:
@Berkay

**Comment by malvonme** [comment]
The issue was just resolved by @trizin! Thx! 

If you feel this is smth worth documenting, feel free to input what you did here, @trizin (optional).

@zippy1979, if everything works fine on your end now, pls comment here as #resolved. 

Thanks for the quick work guys!

**Comment by zippy1979** [comment]
#resolved

**Comment by malvonme** [comment]
Thank you @zippy1979 !
