### ISSUE TITLE
[Project-Guidance WG][Proposal Template][MarCom] R12/R13 - Update proposal templates to: improve process, evaluators UX, and signaling.

### ISSUE THREAD

**Issue by idiom-bytes** [oceanprotocol/oceandao#28]
Problem:
- Projects are delivering outcomes inside of OceanDAO but it's hard to gain insights, and have a consistent format for how they are reporting progress. The existing format is also not lending itself to understanding more macro outcomes (such as money raised, and other successes) has been a generic way for projects to submit updates, and is not leading to the best outcomes.

Towards Solutions R12:
- Implement steps in template + project process, so projects can provide updates, that marcom can use to help signal

Towards Solutions R13:
- Look for other grant processes, and outlines that help projects communicate a more structured roadmap, and outline for their deliverables and contributions. https://github.com/w3f/Grant-Milestone-Delivery/
- R13 solution should address Evaluator UX, milestone progression, and improve upon the existing [Deliverable Checklist]

#### DoD R12:
- [ ] Update current proposal template so projects are required to submit updates/summaries of their progress/release/milestones.
- [ ] Update current Project-Guidance WG agenda, to remind projects that they are required to submit/updates/summaries of their progress/release/milestones
- [ ] Update comms w/ grantees so there is a clear ask to promote/communicate (partial or full) funding via OceanDAO

#### DoD R13:
- [ ] Restructure OceanDAO's template to highlight milestones and improve the outline.
- [ ] Structure the outline in a way that is repeatable, so that Evaluators do not have to undertake a heavy mental load when evaluating each project.
- [ ] Make it easy for someone to look at these project updates, and quickly share successes, and provide signal (i.e. MarCom as a consumer of this content). Project's don't just start and end, they have a rich story, this should be captured as part of this outline.

#### DOD:
- [ ] Get signoff from @AnaLoznianu and @MonicaBotez that process will generate good updates

**Comment by trentmc** [comment]
Obsolete
