### ISSUE TITLE
[OceanDAO Engineering][MarCom] Automate OceanDAO, WG, and Marcom messages.

### ISSUE THREAD

**Issue by idiom-bytes** [oceanprotocol/oceandao#30]
### Problem
Marcom continues to have to support a bunch of repeatable, mechanical messages, that are also hard to capture the information because it's dependent on many summaries.

Automate recurring messages:
- Automate "Upcoming Town Hall", "Town Hall Starting": Tweets, Discord Messages.
- Automate "R11 Is live", "R11 Due Dilligence", "R11 Conclusion": Tweets, Discord Messages
- This does not need to be complicated. DAOBot could generate a row inside of Airtable w/ the required data. This would be executed in the update_funding_round() function.
- How we manage content needs to be figured out. This could be just rows that are generated by DAOBot into an airtable i.e. [Scheduled Messages], with (launch_time, twitter_message, discord_messge, trello_message, x, y, z) and it is all automated via zapier.

### New recurring messages:
- Consider new WG schedules. Perhaps instead of a reminder for each event, send a daily summary of what's happening inside the Ecosystem. Please look at [TEC Schedule](https://calendar.google.com/calendar/embed?src=5mkep1ad1j860k6g7i7fr8plq0%40group.calendar.google.com&ctz=America%2FVancouver) in consideration.

### Content management & automation
- dConsider how to make content easy to add + automate such as daobot + airtable + automations (if avaialble) to auto-send to twitter + discord
- Airtable has integrations w/ zapier, etc...
- We can use a mailer + discord api... however we may want to integrate in more places: telegram, other community/WG trellos, etc...If so, we might want to just pay for these services + automate via Airtable. **Let's leverage tooling as much as possible.**

### Improve content generation:
- Airtable rows w/ scheduled times
- Send tweets to @_OceanDAO
- Send messages to Discord #announcements
- Send updates to WG/Outreach Communities via their Trello -> New tasks to promote the content, etc...

### Definition of Done:
- [ ] Leverage as much off-the-shelf tooling as possible. Airtable + Zapier has been great to test with. I recommend us continuing to asses this direction, and not get carried away in building everything in code as a first step.
- [ ] Automate "R11 Is live", "R11 Due Dilligence", "R11 Conclusion": Tweets, Discord Messages
- [ ] Automate "Upcoming Town Hall", "Town Hall Starting": Tweets, Discord Messages. Automate "WG messages". Consider new WG schedules. Perhaps instead of a reminder for each event, send a daily summary of what's happening inside the Ecosystem. Please look at [TEC Schedule](https://calendar.google.com/calendar/embed?src=5mkep1ad1j860k6g7i7fr8plq0%40group.calendar.google.com) in consideration.
- [ ] Get signoff with @MonicaBotez and @AnaLoznianu  that the implementation is good

**Comment by idiom-bytes** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/OceanDao-60a669231c2ed7000e90684b/issues/oceanprotocol/oceandao/30?planning-poker) with ZenHub @AnaLoznianu @claudiaHash @KatunaNorbert @DimitarSD

**Comment by idiom-bytes** [comment]
@AnaLoznianu @MonicaBotez please help make sure this task is reviewed and signed off by the marketing team.

**Comment by trentmc** [comment]
Automated tweets etc is not necessarily desirable

We now have better defined ops for comms around a given round 

Therefore closing this

**Comment by idiom-bytes** [comment]
`We now have better defined ops for comms around a given round`
Do you know where these are defined or who owns this?
