### ISSUE TITLE
[Working Group][Discord] OceanDAO Eng WG Membership structure

### ISSUE THREAD

**Issue by idiom-bytes** [oceanprotocol/oceandao#31]
This issue was opened as way to increase transparency around responsibilities, expectations, and outcome of the WG.
Please [read our WG outline](https://docs.google.com/document/d/1lV3XPqFlReB89c0cvPfbXENE2NE_-8ppQnSQxSy0ITk/edit?usp=sharing).

#### Problem
I'd like to move all OceanDAO Engineering related conversations into the public. But I worry about having to address anyone who feels like jumping in w/ very tangential topics. So, either heavy moderation (overhead), or gating for the purposes of maintaining signal.

I would personally vote for the latter to reduce overhead while improving membership funnel to have more contributors.

I'm also indifferent of outcome, but I want to make sure there is a clear preamble around WG expectations & outcomes so we can maintain velocity against roadmap.

#### Working group structure
- **Public, but permissioned.** (Public to read, permissioned to write) 
- I want to triple emphasize the **WORKING** part of **Working** Group.
- This means towards clear outcomes that move the needle of our organization.
- This means that all discussions should have a thoughtful issue that is clearly working towards an outcome.

#### Public Access
- Everyone is welcome to view our chat and follow the discussions.
- Everyone is welcome to write issues/proposals to our main github repository.
- We recommend you starting to engage via Dicord and Github first.
- Everyone is welcome to join our calls, write comments, and our meeting agenda will enable non-members to participate.

#### Membership
- You must create a technical issue that gains sufficient traction, or take a technical issue that already exists, is aligned with our roadmap, and help bring it to completion.
- Projects and participants that have gained funding against Core DAO Improvements such as: Pearl, Robin & Tim (Votes4LP), and TEC, may join.
- Our weekly meeting will have an agenda that enables non-members to participate.
- Our weekly meting will also support a ceremony to welcome new contributors into the group as members.

**Comment by trentmc** [comment]
> Public, but permissioned.

This is confusing, because it's too vague. Therefore I have tacked on the following phrase " (Public to read, permissioned to write)". I think this clarifies nicely at a high level. 

> Membership
> You must create a technical issue that gains sufficient traction, or take a technical issue that already exists, is aligned with our roadmap, and help bring it to completion.

This isn't appropriate for non-technical WGs. Even for more technical WGs, it really depends on the WG. What we have so far is "it's the discretion of the stewards". I recommend that we keep that. We can help supply stewards with _guidelines_ for adding members, and removing members. And over time, any WG should shift from "discretion of stewards" to "discretion of WG members".

**Comment by idiom-bytes** [comment]
> This is confusing, because it's too vague. Therefore I have tacked on the following phrase " (Public to read, permissioned to write)". I think this clarifies nicely at a high level.

- I agree, that's better.

> This isn't appropriate for non-technical WGs. Even for more technical WGs, it really depends on the WG. What we have so far is "it's the discretion of the stewards".

@trentmc please see that this was a ticket written specifically for OceanDAO Eng WG.
https://discord.com/channels/612953348487905282/908016934161879080/908166604133646417

I think we should use this simply as an example for other groups to structure their Membership structure & access.

**Comment by trentmc** [comment]
> please see that this was a ticket written specifically for OceanDAO Eng WG.

Ah right! +1

**Comment by trentmc** [comment]
We're in decent shape now, things have stabilized, can close
