### ISSUE TITLE
R18 First Sprint - Adjudicating Deliverables

### ISSUE THREAD

**Issue by idiom-bytes** [oceanprotocol/oceandao#378]
## Proposal Ops:
This ticket represents the work for the last sprint where we have to do OPS to support proposals, and the grants program.
How to do the live-ops [video](https://drive.google.com/file/d/1dtv3eb6MGU5gwrQpz7nAuRLvaqTqn_T-/view?usp=sharing)

### Proposal Support
- [x] Provide support on "How to use Seed"
- [x] Review Port for New Proposals or Proposal Updates
- [x] Provide support on "How to access admin account on Seed"
- [x] Accept / Reject proposal Updates

### Core-Tech WG Support
- [ ] Projects that apply to Core-Tech need to be cleared by the WG

### PGWG Support
- [ ] Communicate to PGWG as projects come online
- [ ] Request support for projects that do not have sufficient OCEAN.

### Comms
- [ ] Prepare proposal summaries for Twitter/MarCom

**Comment by malvonme** [comment]
Done today, will keep open rest of week @idiom-bytes, hence move back to "Current Round" top
