### ISSUE TITLE
R18 - First Sprint - Weekly DAO OPS

### ISSUE THREAD

**Issue by idiom-bytes** [oceanprotocol/oceandao#383]
### **Goal:**
We want  to have all upcoming events of the week as EVENTS in discord (compare: screenshots). 

Ideally, a few days in advance for ppl to be able to plan up front / factor it into next weeks personal Cal. Let's say: every Friday latest, events for upcoming week.

It's still manual for now, event creation, but let's keep an eye on automation down the road. 

### **Benefits:**
- Visibility of our Events
- Deeplinks to invite friends or for us to do Comms with

### DoD:
- [x] You have Admin-Rights in Discord
- [x] You created all events for the upcoming week (WG calls + Town Hall)
- [x]  It's Friday latest, next weeks events are up. Have a ☀️ Weekend!
- [x] It's Monday, and time to tweet out the events of the week on @oceandao_ ! (Find Template below!)
---
### **Text Templates per Working Group / Town Hall:**
(Hint 1:
Use your local time, Discord Events will adapt accordingly. Displayed here in UTC for reference

Hint 2: 
Each working group has its dedicated voice channel (set in first screen when creating event, EXCEPT for Town Halls, the happen in "events voice" channel)

**OceanDAO Parameters & Roadmap WG**
_2pm UTC Tuesday - Every other week_
In this bi-weekly open discord voice we discuss future roadmap items and parameters of the OceanDAO, like earmarks, quadratic funding, balance of power, sibling-attack-protection, etc..

**OceanDAO Engineering WG**
_3pm UTC Tuesday - Every week_
In this weekly meeting, thean OceanDAO Engineering Team sync (core and contributors) in an open discord voice session right here. Learn about the latest BUIDL in OceanDAO Land. 

**OceanDAO Core Tech WG**
_2pm UTC Wednesday - Every other week_
The Core Tech Working Group is directed towards high-impact technical outcomes, including identifying high-priority tech projects (e.g. earmarks), find teams to work on them, and help shepherd those projects to completion.

This voice is bi-weekly and open. If you are interested, feel free to join and contribute to this 

**OceanDAO Town Hall**  
_3pm UTC Wednesday_
Learn about all the latest news and updates in OceanDAO land, including Working Groups, Grantees, new features and budget allocation. 

It's weekly and open for everyone to tune in, learn and discuss all things OceanDAO.   

**OceanDAO Project Guiding WG**
_3pm UTC Wednesday_
If you are your OceanDAO Grant Proposal right now and have open questions, jump on this weekly open voice and connect to experienced project guides.   

Just as much: if you wrote proposals in the past or are an expert in one of our verticals (Data, Blockchain/AI, Outreach, etc.), we love you to join here and start helping new applicants. 

  **OceanDAO Outreach WG**
_2pm UTC Thursday_
In here, we discuss outreach initiatives to build, educate and bring together the Ocean Protocol Ecosystem participants - on a bi-weekly basis. DAO-funded outreach initiatives snc with our ambassadors, comms core team members and trusted community content contributors.

**OceanDAO Project Guiding WG**
_17:00 UTC Thursday_
If you are your OceanDAO Grant Proposal right now and have open questions, jump on this weekly open voice and connect to experienced project guides.   

Just as much: if you wrote proposals in the past or are an expert in one of our verticals (Data, Blockchain/AI, Outreach, etc.), we love you to join here and start helping new applicants. 

---

Tweet Template [MONDAYS] to announce the appointments of the week:

🔔 #OceanDaoEvents of the week🔔

Tuesday:
2pm UTC - Parameters & Roadmap WG
3pm UTC - Engineering WG

Wednesday:
2pm UTC - Core Tech WG
3pm UTC - Town Hall 73

Thursday:
2pm UTC - Outreach WG
3pm UTC - Project Guiding WG

Links top left @Discord 📸

📅Cal:
https://calendar.google.com/calendar/u/0/embed?src=tbrqabcs2jopm1dnehp274k62g@group.calendar.google.com&ctz=Europe/Berlin

<img width="252" alt="Bildschirmfoto 2022-05-09 um 17 27 15" src="https://user-images.githubusercontent.com/101562291/167444281-85b87f72-7a53-4a51-8966-0a95e9308fdd.png">

**Comment by malvonme** [comment]
Added 4th DoD item (Comms Measure no weekly events -> Twitter).

Also, find an example here:
https://twitter.com/OceanDAO_/status/1523686339757375489?s=20&t=wqTMI1Olin2YoHG7PKkR0g

Moving this to QA, will need equal reminder next week (guess moved back to Backlog after you've seen this 🤙)

**Comment by malvonme** [comment]
Also polished the events templates a bit, so that, worst case, a complete stranger could do this instead of / on behalf of us (scalability).
