### ISSUE TITLE
R18 - PGWG OPS - Initialize Coordinape Epoch

### ISSUE THREAD

**Issue by idiom-bytes** [oceanprotocol/oceandao#386]
## Overview
The PGWG needs to deploy a Coordinape Epoch every round so that we can coordinate around our tasks and goals.

### DOD: PGWG
- [ ] Coordinape Circle has been updated to adjust for any membership changes.
- [ ] Coordinape Circle has been kicked off.
- [ ] Guides have gathered in kickoff meeting, discussed epoch, and celebrated launching the new round.

**Comment by malvonme** [comment]
I have created the new Epoch (5 days, till sunday, standin/fallback for the past epoch):
https://app.coordinape.com/admin/circles![Bildschirmfoto 2022-05-17 um 17.14.54.png](https://images.zenhubusercontent.com/6230bfd994a5cba772c63765/a5e52f5a-d9fe-42dd-b82d-f9ded4a54ebb)
