### ISSUE TITLE
Product OPS: Outdated Earmark for mpowered ("Outreach"), broke OceanPearl leaderboard

### ISSUE THREAD

**Issue by malvonme** [oceanprotocol/oceandao#389]
### Goal:****
Get Oceanpearl.io leaderboard live again asap. Background: OPF main handle just tweeted the Call-to-Action to vote for Round 17 (150k followers, biggest lead we get):
https://twitter.com/oceanprotocol/status/1522532353628774400?s=20&t=naobozks5NjlYePDz8uEFw

At the same time, an Earmark was not fully successfully assigned to mPowered, as they went under Outreach THIS TIME (event), but nobody else had this earmark, hence 
- it was "not produced" this Round, 
- hence inconsistency in the calculation, 
- hence: OceanPearl broke.

### **DoD:**
- [x] Interim fix: @malvonme changed the Earmark for mPowered to an currently active one, "Core Tech Earmark", so the calculation can work on Pearl, and we don't lose the voter traffic
- [ ] Sustainable fix: would be great for @idiom-bytes @KatunaNorbert or @idiom-bytes to posthume create the "Outreach Earmark" (not new outreach) and assign mPowered to it 

Cheers!

Also thanks to @Abrom8 for being insta-available, even in a meeting, to resolve this with me / hint me towards the fastest solution. 🌊☯️🥷🙌

Also compare screenshot: unproduced earmark

[EDIT]: "Outreach" is an outdated earmark. Compare comments below. Will be reviewed in Review today, 1:30pm UTC. 

![unknown](https://user-images.githubusercontent.com/101562291/167130448-d0387d62-5b43-4af2-a3d4-0d67a42eb0c4.png)

**Comment by malvonme** [comment]
Update, thx to @KatunaNorbert giving me context: "Outreach" (as in: NOT "New Outreach", but general) is an outdated earmark that doesn't exist anymore. 

It is unclear for now how mPowered got under this Earmark still, wether it is a bug in the frontend or if we adjusted the earmark manually for him posthume (I remember losesly, busy week, @idiom-bytes having had contact w/ mpowered/corrie on this, no?)

Let's look into this today in Review. 

Not sure about the political implications too, as I know there have been discussing around outreach activities for Core Tech Project, also wrt to the earmark. 

Alternative would be to put this mpowered proposal in General, but I don't want to tweak the Airtable a second time manually without consulting the dev-team before. 

Review is in 1h.

**Comment by Abrom8** [comment]
Thanks @malvonme for the fast response time!

**Comment by malvonme** [comment]
@idiom-bytes, we didn't get to this in review today (we took care of being human instead for 30min, syncing over the week, important!), maybe look into this later today or Monday -> mPowered does Outreach mainly this round, still CORE TECH earmark, or GENERAL?

Feel free to readjust to your best assessment. 

Have a great weekend later!
