### ISSUE TITLE
[OceanDAO][WGs] WG Scaffolding - Identify remaining WG's and provide [Basic Tools]

### ISSUE THREAD

**Issue by idiom-bytes** [oceanprotocol/oceandao#39]
#### [Problem]
As we try to leverage groups, orgs, pods, networks, of people within OceanDAO, how do we increase transparency/accessibility, while lower overhead/friction.

**[Channels: Tech Ship + Outreach Ship]**
They have been meeting towards restructuring/re-mission
They have 2 channels inside of Discord
I'd like to identify what direction they are taking, and how to feature/leverage/include them as part of WG's.
It's not very clear how we're continuously aligning between these groups.
**[Channels: Academy]**
Does this channel exist just because of our funding? Most of that funding is going to digital outcomes.
Where does this sit between Granted Project & DAO Lego?
Let's connect with them, and identify how to onboard these WG's.

**Immediate:** Just give them same same as WG - [Basic Tools] (please read below).

#### [Further Problem Statement]
These groups/circles/projects have their own channels and processes.
Because they have self assembled in a variety of ways, there is a lot of friction to navigate between these groups.
Further, we're not really supporting them from an integrations point of view... Example: Put their meetings in Ocean Ecosystem calendar.
Their processes, missions, outcomes, are not really visible to the community or celebrated.
These are good community projects, and we should perhaps increase visibility/engagement/contributors/outcomes.

### [Basic Tools] - WG DoD
- [x] Put them in our ecosystem calendar
- [x] Have them participate in a WG that can serve their focus
- [x] Turn them into WGs
- [x] Improve their content pipeline so meetings are recorded, increased engagement, etc..

**Comment by MeMent0L** [comment]
These projects need support and visibility. I can speak for the Ocean Ambassador group and the Ocean Academy. 

**[Ocean Ambassadors]**
There is only one group now, and we could have just 1 channel in Discord called Ocean-Ambassadors.
The Inn, Tech-Ship and Outreach-Ship channels can be removed (and members re-allocated to Ocean-Ambassadors.

Here is some background on the group: 
- https://docs.google.com/presentation/d/1JBrm0oEJHdqHAs8Llyx6tA9DR6R6VQ0EYiILn8aUSLg/edit?usp=sharing

It highlights our proposed structure, improvements, KPIs and roadmap.

This group should definitely be part of Ocean Protocol discord, and meetings/planning should be better integrated. We had a coordination meeting with OPF/Marcom in December to set a process for ongoing communication and collaboration. 
- We will have a monthly meeting to get the priorities from OPF/OceanDAO
- Key members of OPF/OceanDAO have joined our TG group to be able to interact anytime and see what we are up to

There are 8 other WB within Ocean Ambassadors to step-change the group's contributions to Ocean Protocol. 
Here is the detail of our current priorities to deliver on our objectives:

1. Step-change onboarding process : https://trello.com/c/68rPR0OV
2.a. Create Activities Management process: https://trello.com/c/5k1wMZiy
2.b. Set up supporting tech stack for activities submission & voting: https://trello.com/c/mVmB4IGq
2.c. Design Ambassador DAO (economic/social design, supporting tech stack): https://trello.com/c/vh87n4IC
3. Define list of Activities with standard rewards on i) delivery and ii) performance:  https://trello.com/c/4YdzM9vM
4. Define Ambassador perks (gear, badges, recognition): https://trello.com/c/9umCyiNu
5. Communication strategies to maximize visibility across channels: https://trello.com/c/oYqi4tWa
6. Integration of processes with OPF/OceanDAO: https://trello.com/c/IbUyozJp
7. Deliver new Ambassador website: https://trello.com/c/t5dgyNsD
8. Deliver new Ambassador Pledge & Manual: https://trello.com/c/atLqN3dF
9. Blast the most awesome video produced on Ocean Protocol:  https://trello.com/c/wwC7yfWL

Funding for these efforts could be in earmarked in OceanDAO. Not sure in what WG this should be discussed.

Finally, what is the process to update Ocean Ecosystem calendar?

**[Ocean Academy]**
Ocean Academy provides basic introduction/understanding of Ocean Protocol for newcomers and serves as a credentialing  for new Ambassadors (Ocean101 completion is a requirement).

This project is now a standalone project, which established a legal setup in SG, has a vision to become its own DAO, and that gets its funding from OceanDAO [outreach category].

Here is the background on the group's vision : https://docs.google.com/presentation/d/1zmCw0jP3RBaU_brdiJolL8aS01Vq2yl5thVdQtgt_pg/edit?usp=sharing

The discord group may be kept if you see value in it. From the project perspective it can help with recruitment, but we are not actively using the channel; work and discussions happen through Telegram, Trello and Twitter.

**Comment by idiom-bytes** [comment]
Me and @MeMent0L, worked together to resolve this issue by:
- Archiving Outreach + Techship channels
- Updating Inn -> Ambassadors
- Integrating Ambassador meetings into our calendar + providing extra visibility into Ambassadors

There are other improvements we can do (i.e. meeting recordings) but we can tackle these at a later date. I propose we close this issue.
