### ISSUE TITLE
BrightID boost not processed when voting?

### ISSUE THREAD

**Issue by malvonme** [oceanprotocol/oceandao#390]
### **Issue:**
One of our DAOmembers, Trishul, reported, that despite having properly performed the 400% boost on our website, and properly having done the initial BrightID Zoom call verification as well (already clarified in Discord thread), she still does not get the 400% boost when voting power is calculated on Snapshot. 

Find the report here:
https://discord.com/channels/612953348487905282/776848812534398986/972421039894179870

### **DoD:**
- [ ] Look into Trishul's wallet address in backend to see if hickup:
- [ ] Feedback Trishul in Discord when issue is resolved (or further steps needed)

**Comment by trishulmuchintala** [comment]
Hi guys,

My wallet address :  0x8f06a2bcC62B192ccFE1430B2C38cE78ddFd1480

![Screenshot (42)](https://user-images.githubusercontent.com/44029683/167263952-bda04789-25d6-41f8-9aa6-5e1afe71ff60.png)

I already voted for Indian Ocean Program with 7.6k votes

**Comment by trizin** [comment]
This is not a bug, if you are verified after the voting has started, the Brightid boost will not work as the snapshot has already been taken.
The voting power on the Snapshot is calculated for the snapshot block number. The website uses the latest block number to calculate.
