### ISSUE TITLE
Web3Tools - Report subgraph and delegation errors to user and improve error UX

### ISSUE THREAD

**Issue by idiom-bytes** [oceanprotocol/oceandao#393]
Issue #1:
We have now experienced a couple of times the subgraph coming down, and not reporting the latest blocks. This causes an error inside of our web3tools dashboard, and is unable to report the proper voting power.

In this case, we should let the user know "Subgraph not up to date, please let the OPF team know on Discord or oceandao@oceanprotocol.com" and do not report the voting power or other information on the screen.

Issue #2:
Users may connect to this dashboard but not have any delegates.
![Screenshot from 2022-03-28 13-21-53](https://user-images.githubusercontent.com/69865342/160480552-3596fddc-b2ba-4d8b-b2f9-731bf42fb804.png)

### DoD:
- [x] Report any subgraph errors to users to they have a clear indication as to why the tool isn't working at the moment
- [x] Report any delegation errors to users (they do not have any delegates) to they have a clear indication why they are not receiving any additional votes

**Comment by idiom-bytes** [comment]
https://github.com/oceanprotocol/site/pull/1450

**Comment by trentmc** [comment]
oceanprotocol/site#1450 got merged into staging branch of site repo

We will close this ticket, with the assumption that staging will get merged into main soo enough
