### ISSUE TITLE
[OceanDAO][WGs] WG Scaffolding v0.1 - Create an outline and process to deploy a v0.1 WG Scaffold.

### ISSUE THREAD

**Issue by idiom-bytes** [oceanprotocol/oceandao#40]
#### [Problem]
As we work to onboard community, and help provide them with the tools they need to organize, form working groups/pods/squads, of people within OceanDAO, how can we increase transparency/accessibility/leverage, while lower overhead/friction.
- There are many WGs being deployed
- We need scalable ways for these groups to be autonomous and self-managed
- We should support a v0.1 implementation for WG's that improves overall transparency & lateral contribution between WGs
- We should offer 1 basic implementation.
- We cannot make everyone happy.
- I believe we should look again at TEC, to identify a stack. I.E. I believe they are leveraging Github + Discord + Sourcred. Which, I believe is a solid stack. However, not every group might benefit from it (i.e. many people that do marketing have no idea how to use github).

#### [Towards a Solution]
Provide a v0.1 WG scaffolding on a "5 minute button click" (let's start with 2-4 hours of deploy), that can provide the infrastructure for these orgs to operate. 

Provide the required systems to perhaps fund, and incentivize them (Coordinape / Sourcecred). The scaffolding would provide the tools, the teams would manage the fund distribution (i.e. gnosis safe multisig could also be part of scaffolding).
- Provide [Basic Tools] - Discord channels, roles, wg outline & requirements, gdrive folder
- Content Pipeline - Video Capture + Publishing Pipeline: OBS + Discord + Record => GDrive/Airtable
- Github + Sourcecred | Coordinape + Polygon Distributor

#### Extrapolating technical requirements:
- [Basic Tools]
- [Content Pipeline]
- [Github]
- [Sourcecred]
- [Coordinape + Polygon distributor]
- [Gnosis Glue]
- [Funding Processes]

#### DOD:
- [x] Create outline for v0.1
- [x] Deploy stewards + Project-Guidance WG with v0.1.

**Comment by idiom-bytes** [comment]
Project-Guidance is already leaning towards wanting to setup a reward systems before onboarding participants. 

So, people are talking about externalities before even delivering value. I believe this should be reversed.

**Comment by idiom-bytes** [comment]
Other tools suggested:
https://miro.com/

**Comment by MeMent0L** [comment]
And [disperse.app](https://disperse.app/) for mass sending of tokens on Polygon [Polygon Distributor]

**Comment by VideoWiki** [comment]
Would like to propose Video.Wiki for meetings and townhalls.

**Comment by idiom-bytes** [comment]
This task is now done.
As we iterate and improve these WGs, we can look at change tooling and evolving the software we use. 

VideoWiki's recommendation is great, however we only had a few people running the WGs and were still getting these processes in place.

I propose we close this task, and open others based on new requirements that come up.
