### ISSUE TITLE
[Project Guidance WG][ROI vs. Value] R12 - Soften DAO grant processes & focus more on adding value

### ISSUE THREAD

**Issue by idiom-bytes** [oceanprotocol/oceandao#41]
High level description of the goal.
https://blog.oceanprotocol.com/introducing-oceandao-working-groups-db920b14a5d8

The project-guidance WG will help projects focus on adding value.
https://docs.google.com/document/d/1kw4UwJHZaCf5PKvU3ONoN5nSj-r5zZAX2KJCqzJFT7M/edit?usp=sharing

#### Project Criteria
Ways that a team might add value:
- Usage of Ocean
- Viability
- Community active-ness
- Adding value to overall community

#### DOD
- [x] Update [wiki](https://github.com/oceanprotocol/oceandao/wiki) and our [definitions for ROI](https://github.com/oceanprotocol/oceandao/wiki/On-ROI)
- [x] Update townhall & other supporting copy to reflect updates
- [x] Update website to reflect updates. Includes: change OceanDAI page, "ROI+" section's title & content to "Value add" title and apprropriate content within. Also, anywhere else in site that "ROI " is mentioned should get tweaked.

Q: how to Reconcile how value-add still means ROI>1? Trent's A: content in blog post is enough, if we use it elsewhere that's ok.

**Comment by idiom-bytes** [comment]
I do not think this is a dev task.

This is mostly a task for Project-Guidance WG, to update wiki, templtae, and other parts inside of the Proposal pipeline. @anapheys should be able to help drive this forward.

@CatalinUXS 
The website related updates should just be [updating the content.json](https://github.com/oceanprotocol/site/blob/main/content/pages/dao/dao.json) and should be doable by anyone.

Thank you for being engaged, but I'm removing you from this ticket. :)

**Comment by anapheys** [comment]
PG Working Group Folder:


https://drive.google.com/drive/folders/1d-wWyyFdv6pZ0H69pyPWytYNck6sdeOV?usp=sharing

**Comment by idiom-bytes** [comment]
Website should have been updated a long time ago.

https://github.com/oceanprotocol/site/pull/1340
