### ISSUE TITLE
[OceanDAO][WG] Deploy V0.1 Scaffolding for 2 key WGs

### ISSUE THREAD

**Issue by idiom-bytes** [oceanprotocol/oceandao#42]
I believe both:
- Stewards
- Project-Guidance WG

Would be good recipients for V0.1 Scaffolding.
- Stewards would eat their own dogfood
- Project-Guidance would acquire a work-funding structure, to give proper incentive for participants to engage

Tasks outlining WG [Basic Tools] + [V0.1 Scaffolding]:
https://app.zenhub.com/workspaces/oceandao-60a669231c2ed7000e90684b/issues/oceanprotocol/oceandao/40
https://app.zenhub.com/workspaces/oceandao-60a669231c2ed7000e90684b/issues/oceanprotocol/oceandao/39

**Comment by trentmc** [comment]
Done as needed
