### ISSUE TITLE
[DAO WGs][Outreach][Steward] TEC - Help TEC host a presentation on Discord WRT: CV and Bonding Curves

### ISSUE THREAD

**Issue by idiom-bytes** [oceanprotocol/oceandao#43]
I need help finding someone to help host a TEC presentation on bonding curves and Conviction Voting.

> Hey @Idiom | Ocean and @Alex N | Ocean Protocol - Can I put you in touch with our Comms WG lead aboust hosting a TEC session on yoru Discord server? It will be one of the params parties that we are hosting on our own server and a number of other communities. This is the dashboard that we would like to demonstrate and use to educate other communities about Augemented Bonding Curve and Conviction Voting. https://config.tecommons.org/

#### DOD:
- [ ] OceanDAO Steward + TEC Steward host an event inside of public Discord voice channel.
- [ ] "Can you can add it to your community calendar?"
- [ ] "Can you retweet the promotion we send to you?"

**Comment by idiom-bytes** [comment]
@anapheys @sheriff4 @razvan-ol @trentmc, who could help deliver this?
- [ ] Calendar: Update the Ocean Ecosystem Calendar
- [ ] Community: Make announcement to community
- [ ] Hosting: Help host the event (and record, and share it)
- [ ] Marcom / Outreach: Twitter announcement @MonicaBotez @CasianaOcean

**Comment by trentmc** [comment]
Option 1: treat it as a "deep dive" following a Town Hall. 

Option 2: have them present to "Parameters & Roadmap WG" during one of that group's meetings.

I lean to (1), but ensuring that "Parameters & Roadmap WG" members are well aware of the talk, so would be present.

**Comment by idiom-bytes** [comment]
I feel that Option 3 is the most direct thing being asked here: Treat is as a community event.
1. TEC is trying to broadcast this as effectively as possible across multiple channels, rather than doing multiple presentations.
2. This should just be a request that any steward can take.
3. This should just be a community event.

Finally, I'm not 100% sure how this should take a full session inside Params + Roadmap WG

**Comment by trentmc** [comment]
I'm fine with Option 3. Given that, I'd leverage Ocean Marcom to help.

**Comment by MonicaBotez** [comment]
I prefer Option 1 [deep dive after a TH] because this will improve the participation to Ocean Town Hall. This being said, let's set a date and we will take care of visual and promotion. Do I write to Angela and copy you? Or how we should advance with this? Thanks.

**Comment by idiom-bytes** [comment]
I'm going to invite @CasianaOcean to the discord conversation, and she can take it from there.

**Comment by idiom-bytes** [comment]
We did have a 1.5hr meeting hosted by Angela, but there was no other event hosted in public.
Proposing this task is closed.
