### ISSUE TITLE
Potential Portal Bug (or legacy/migration hiccup) with Homomorphic Encryption Proposals

### ISSUE THREAD

**Issue by malvonme** [oceanprotocol/oceandao#430]
### **Challenge:**
Simon is currently trying to create a new proposal, but gets 2 repetitive bugs. Both are documented in Discord right here, revolve around creating new proposals in Portal to an existing project (pre-portal).

Farming is prio, would be good to look into it a bit ahead of submission deadline for next round (June 7). 

Link to conversation, to follow up with Simon Founder:
https://discord.com/channels/612953348487905282/908016658239610920/973980960842453062

### **DoD:**

- [x] Reach out to Simon, either through Discord above, or E-Mail: 
s.pfeifhofer  @  tributech.io
- [x] Potential Bug is looked into and identified
- [x] Alternatively: Simon is informed about the best practice to fix (check both if 1 done)
- [x] Simon published his new Homomorphic Encryption proposal

*Assigning me and @idiom-bytes to avoid single-point of failure and ensure visibility in dev team when prioritizable

**Comment by simonpfeifhofer** [comment]
@idiom-bytes @malvonme or anyone reading this and having further questions please contact me.

**Comment by simonpfeifhofer** [comment]
@malvonme: All 4 points of the DoD fulfilled!

**Comment by malvonme** [comment]
Thx for providing us with all necessary info, Simon! 🙌

Thx for supporting and helping to close this, I think @trizin 🙏

I saw your new proposal is live now, Simon, so I will close this. 

Thx everyone
