### ISSUE TITLE
[DAO][Quadratic Voting][3Box][Registries] Expand QV support by adding other registries & verification systems.

### ISSUE THREAD

**Issue by idiom-bytes** [oceanprotocol/oceandao#50]
#### Problem:
- Our OceanDAO page w/ identity verification will only support Bright ID.
- We may not get a lot of conversions via Bright ID
- The more we increase conversions, the more QV is effective. 
- Adding another DID, and bonus, may lead to further conversion.

#### User stories
- [ ] As a user, I have a couple of options to increase my voting power.
- [ ] As a user I can go to op.com/dao/QV page and register to the **3Box Ocean Marketplace** to improve my overall voting power.
- [ ] As a user, my voting power from **3Box Ocean Marketplace Registry** receives a bonus and is taken into consideration in the Snapshot.js strategy
https://app.zenhub.com/workspaces/oceandao-60a669231c2ed7000e90684b/issues/oceanprotocol/oceandao-private/333
- [ ] As a user, my Final Voting Power = Voting Power * SUM(BonusA, BonusB, BonusC)

**Comment by trentmc** [comment]
Not urgent, if it becomes an issue, it will rear its head. So closing
