### ISSUE TITLE
Calculation of Voting Power fails on our website

### ISSUE THREAD

**Issue by malvonme** [oceanprotocol/oceandao#519]
Challenge:
The API used to calculate the voting power seems buggy or defunct (at least since yesterday), returning an error when trying to calculate voting power. Might be temporary. 

Goal:
Calc works without errors. 

DoD:

- [ ] Voting Power (incl. boost) and delegates (incl. power) are displayed properly on:
https://oceanprotocol.com/web3Tools
![Bildschirmfoto 2022-07-04 um 20.16.15.png](https://images.zenhubusercontent.com/6230bfd994a5cba772c63765/daa85009-a1c7-4df9-91bb-5ffbf573d213)

**Comment by malvonme** [comment]
Update:
This bug seems permanent now. Been defunct for about 3 days. (compare screenshot)[Uploading... Bildschirmfoto 2022-07-06 um 14.32.53.png]

**Comment by idiom-bytes** [comment]
We need to make sure that this is working correctly.

It could be that the v3 subgraph is down.. or something else??? 
@trizin, please help.

**Comment by idiom-bytes** [comment]
Still getting the same bug.![Screenshot from 2022-07-07 18-48-30.png](https://images.zenhubusercontent.com/601eeb154030993736fc619e/7d6ada87-e800-4304-8856-a2c6d612b8b4)

**Comment by KatunaNorbert** [comment]
@malvonme @idiom-bytes Is this still an issue?
For me it's fixed now after the snapshot strategy update

**Comment by malvonme** [comment]
It's still failing

@KatunaNorbert @idiom-bytes 

![Bildschirmfoto 2022-08-02 um 15.32.42.png](https://images.zenhubusercontent.com/6230bfd994a5cba772c63765/8f529554-777e-4831-9d56-028c128a3206)

**Comment by KatunaNorbert** [comment]
Fixed inside:
https://github.com/oceanprotocol/site/pull/1502
