### ISSUE TITLE
in wiki, "value add" link at bottom of page links to wrong wiki page

### ISSUE THREAD

**Issue by TimDaub** [oceanprotocol/oceandao#54]
<img width="719" alt="Screen Shot 2021-11-29 at 12 26 29" src="https://user-images.githubusercontent.com/2758453/143859900-8dbc2399-e2dc-4739-995a-2a8a9bd3929b.png">

"Value-add" links to https://github.com/oceanprotocol/oceandao/wiki/Value-Add but at that page is nothing.

here's the actual value add page: https://github.com/oceanprotocol/oceandao/wiki/project-criteria

**Comment by idiom-bytes** [comment]
Hi Tim, just going over some tickets. 

Thanks for submitting this bug, I have now updated the wiki and am closing this ticket.
