### ISSUE TITLE
[DAOBot] R12 - Project is complete, but state is showing up as "Unreported".

### ISSUE THREAD

**Issue by idiom-bytes** [oceanprotocol/oceandao#55]
From meeting. Problem:
- DAOBot update executed and project did not update properly
- Previous proposal had been fully completed "all deliverables checked". 
- Current proposal state set to "Unreported".

### DOD:
- [ ] Review airtable example.
- [ ] Copy airtable csv data for that project into code => Try to replicate issue in code base.
- [ ] Update test coverage to show error taking place,
- [ ] Fix bug by updating DAOBot code so that the right state is being selected.

**Comment by DimitarSD** [comment]
the issue was fixed with the latest updates
