### ISSUE TITLE
Latest voting results weren't reflected in Reward Strings

### ISSUE THREAD

**Issue by malvonme** [oceanprotocol/oceandao#563]
Challenge:
There has to have been a small hickup in Airtable / Bot at the end of the voting period:
- Oceanpearl couldn't reflect the last vote that came in (2.5mio OCEAN) in their leadership-board R19. After they "rebooted" this noon, the actual results showed. 
- Same counts for the Reward Strings:
Walt.ID wasn't in the winning section at all before that last vote, is now with about 12K USD. Yet, they have no reward string showing to claim
https://airtable.com/shrZY5n5lukUGSigt/tbls5o7pVfAUU39eX

Reference:
You can take DataMarketCap as second reference. Before this last vote, they had 0 or 1 down vote. After this last vote (not reflected in OceanPearl last night), they had about 40,000 down votes. 

DoD:
- [ ] Have reward strings for all winners from Snapshot/Notion/OceanPearl current state available in https://airtable.com/shrZY5n5lukUGSigt/tbls5o7pVfAUU39eX
- [ ] OPTIONAL, LOWER PRIO: Find root cause, fix

**Comment by philpotisk** [comment]
Thanks for raising and fixing this issue. I see walt.id now in the list https://airtable.com/shrZY5n5lukUGSigt/tbls5o7pVfAUU39eX However, I am still missing the reward-string. Maybe you could add this somehow?
