### ISSUE TITLE
Themistoklis Round 20 Proposal BUG

### ISSUE THREAD

**Issue by malvonme** [oceanprotocol/oceandao#588]
Situation:
Themistoklis/Alex submitted his deliverables. I reviewed them and accepted them. 

Still they are shown as rejected in OceanPearl Projects:
https://oceanpearl.io/projects/560Aaa4DCB-project-themistoklis

And in Airtable:
https://airtable.com/appVer8ccYGnqSm2H/tbls5o7pVfAUU39eX/viwSVKN933jigdJt9?blocks=hide

None of my comment to be found in Port:
https://port.oceanprotocol.com/t/project-themistoklis-python-to-ocean-3d-world-round-20/1989

DoD:
- [ ] Round 20 Proposal of Themistokles must be live by End of Day (End of Submission Deadline) today

**Comment by trizin** [comment]
Seems like they don't have enough OCEAN in their wallet and I'm not sure you can accept their deliverables; the round didn't even start.

**Comment by malvonme** [comment]
-> I meant I accepted their deliverables from last Round. I assumed "rejected" would indicate the "deliverables were rejected". 

Thanks for clarifying. 

What's my fastest way to get them greenlighted?

Reach out to Alex, make sure he hast 500 in his wallet, and submit the proposal again?

**Comment by malvonme** [comment]
@trizin I reached out to Alex, he is submitting again. Thx again for info

**Comment by alextitonis** [comment]
Hey, it doesnt let me re-submit a proposal (got the ocean now, my bad), it says i already have a proposal for this round

**Comment by trizin** [comment]
Hi @alextitonis, you don't need to re-submit. Your proposal is accepted.

**Comment by malvonme** [comment]
Update @trizin Think it is a bug. He cannot submit the proposal again/newly now, as seed tells him his proposal is already delivered for this round? Smth I can do in Airtable?

<img width="650" alt="Bildschirmfoto 2022-08-02 um 16 01 04" src="https://user-images.githubusercontent.com/101562291/182394503-d0187273-e7e2-411b-b0b2-f757f35f2eef.png">

**Comment by trizin** [comment]
He doesn't need to re-submit. His proposal is already accepted. A project can't submit multiple proposals for a round. If you'd like to make a change you can update the proposal via the portal.

**Comment by alextitonis** [comment]
Btw it still says rejected in oceanpearl (tried to update values in-case it would update it - got 600 ocean in the wallet)

**Comment by malvonme** [comment]
Even though this ticket was pushed back to New Issues, I would love to tag you, @trizin, again, so we can follow up on this together.

**Comment by malvonme** [comment]
Alright:
So Alex(Themistoklis), you're project is now officially accepted in our system, Seed Portal, and Port, and I expect it to be votable on in Snapshot when voting goes live. 

OceanPearl also reacted and will make sure that you will appear on the leaderboard:
https://discord.com/channels/836661036526075974/836661440978223165/1004058091748339853

**Comment by malvonme** [comment]
Thank you for helping, @trizin. Thank you Sebastian from Pearl for supporting, best of success to Alex for the upcoming round. Themistoklis is live. The ticket will be closed.
