### ISSUE TITLE
Remove links from wiki and oceanprotocol.com/grants and sunset any interfaces for grants program

### ISSUE THREAD

**Issue by idiom-bytes** [oceanprotocol/oceandao#625]
To reflect the pause to the grants program we should make adjustments to oceanprotocol.com
- Update splash page to communicate the program is paused
- Remove links to any proposal portals, or visuals/comms that may indicate there are funds/grants available
- Update wiki and any other secondary places where we might have links and information about the grant program, to communicate that it's paused.

**Comment by trentmc** [comment]
Duplicate with https://github.com/oceanprotocol/df-private/issues/33
