### ISSUE TITLE
--------------------

### ISSUE THREAD

**Issue by idiom-bytes** [oceanprotocol/oceandao#7]

**Comment by idiom-bytes** [comment]
Hi, in reflection of our chat today, bottom-up growth, and leveraging the DAO, I'd like to propose we reach out to:
Go-To-Market research team
https://port.oceanprotocol.com/t/proposal-go-to-market-analysis/592
Alternate Future Summit team
https://port.oceanprotocol.com/t/the-alternate-future-summit-internship-hackathon/671

In particular I'm looking to:
Understand their projects a bit better (Go-To-Market has been asking for a call)
Include a CTA in their process to promote further OceanDAO grants
In particular w/ Alternate Future Summit: 
Just an intro call for now
They have done an online summit
They are experienced with organizing events/recording/etc
They are planning to do an internship/hackathon around OceanDAO (maybe low R:R)
They are also planning on doing a bunch of youtube videos (maybe good R:R)
They are planning on doing social media camapaigns (probably low R:R)
I'd like to see what they are up to, and if there is any alignment re: DAOWeek/DemoDay/Event coordination

**Comment by seldamat** [comment]
I think this is a great idea! Please do make the products of the feedback / interaction public so the DAO can learn from any developments and stay up to date.

**Comment by idiom-bytes** [comment]
Hi, we are working with a new project management software.
