### ISSUE TITLE
[Parameters & Roadmap WG] Should Unleash Data category have funding restrictions, or be open like other categories?

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/oceandao#73]
**Discord poll**: https://discord.com/channels/612953348487905282/908016760190537798/920222881378607135

**Background**
"Unleash data" is a category side-by-side with "outreach" and other categories.

As of R11, "unleash data" funding got restricted compared to other categories. It was like that for R12 too.

**Alternatives**

Approach 1 - status quo - restricted 

Approach 2 - Make "unleash data" par with the rest again.

Approach 3 - other? Suggestions?

**Comment by w1kke** [comment]
These are the steps needed for a contribution in the "Unleash data" category:
- Collection and cleaning of the data
- Hosting the data + infrastructure
- Providing initial liquidity for the data asset on the marketplace

From this point on this is a pure profit endeavour as the participant will then make $OCEAN on each sale of the data asset.

A proposal to the category will then provide funding to pay for these steps.
With Ocean Data Farming these sales will then be additionally incentivised another time.

This will then add even more $OCEAN on top of all data sales.

From the other categories point of view they are not directly leading to profit + Data Farming rewards. So applying to this category and trying to hit datasets that sell is highly lucrative as it does not entail any risk on the behalf of the proposal creator but potentially yield maximum returns.

The new rules for the category are asking for a proof of sales before further investing into a project that wants to do this.
As the process to get to a good amount of data for sales can be very expensive a lot of investment might be needed for such a project.

I would suggest to ask for some proof of usefulness and try to make it necessary to have positive user feedback for the data before investing more into a dataset. And also asking a dataset that wants to be created to estimate the total costs for it, going round by round is going to be difficult for voters to understand.
Also the benefit for the ecosystem with one more listed dataset is relatively small compared to other tech building more generalised solutions on the protocol.

**Comment by idiom-bytes** [comment]
A discord poll has been launched for this issue. It can be found below.
https://discord.com/channels/612953348487905282/776848812534398986/920221130701275156

**Comment by trentmc** [comment]
**Comment by Tobias @tmanthey [from discord](https://discord.com/channels/612953348487905282/908016760190537798/917844093252563004):**

What worried me today is that Ocean rather burns a Million USD than fund data projects.

Ocean is giving up its fundamental grant category. The only category that builds the "data economy" rather than tools for the data economy. 

Imo double standards are applied when claiming that data projects did not yield data consume, while ignoring that most if not all other projects did not yield hard return either. So following the the argument: "77k did not yield data consume, so why should we fund it" could then basically applied to many projects that consumed even more.

If the fundamental concepts on how the data economy works are not explored, what tools are we building?
I'd like to reference my proposal I made in the data-consume wg. [see below].  Refine "unleash data" category to build high quality promotional data assets for 1 Ocean that then get distributed by the teams incentivised by data farming rewards 

**Comment 2 by Tobias [from Discord](https://discord.com/channels/612953348487905282/908017050646085652/917479014074040350)**
My proposal is to:
1.) Refine "Unleash data" category to "Promotional data". Data under this category must be published on Ocean Market for e.g. 1 Ocean
=> This has a first positive effect on the DAO as it increases the utilization of the available funding, adds more projects to the DAO and leads to more competition
2.) "Promotional data" funding synergizes with Data Farming
Creating data and publishing is not enough for DCV. What we need an incentive to actively promote and support the published data. For this aspect data farming is the perfect incentive. To avoid double dipping I would deduct farming rewards from grant requests.
But this creates in incentive to create  farming rewards higher than the grant funding cap per project

**Comment by trentmc** [comment]
> What worried me today is that Ocean rather burns a Million USD than fund data projects.

This is a valid concern. 

There's intense discussion to change this to "recycle" instead, see:
- #49
- [Related discord poll](https://discord.com/channels/612953348487905282/776848812534398986/915360169452535849) 

From the sentiment in that issue / poll, the consensus seems to be to recycle not burn.

**Comment by idiom-bytes** [comment]
Discord poll for this topic [can be found here](https://discord.com/channels/612953348487905282/908016760190537798/920222881378607135).

**Comment by trentmc** [comment]
Datapoint: "unleash data" category was never intended as solely "get a grant to construct/improve your own handful of datasets, to sell". It was actually much more open-ended than that, you can see examples in the OceanDAO wiki [Proposal Ideas](https://github.com/oceanprotocol/oceandao/wiki/Proposal-Ideas) under "Unleash Data" Category. This includes two big categories:
-  Business / networking based -- not technical. Hitting the phones, calling data brokers, etc
- Integrations to data services -- technical. Integrating chainlink, etc.

In practice, the only teams that had applied were for "construct/improve datasets".

**Comment by trentmc** [comment]
The Parameters & Roadmap WG met yesterday to finalize this issue. Discord votes are taken as an input sentiment, not as the final say. The final say is in the WG.

- Discord votes: 3 “hold”, 2 “modify”

_Discussion:_

- Tobias: (repeated proposal on “promotional data"; and) Data farming won’t be a while yet
- Trent: (read out summary of thoughts). I therefore voted for making it par
- Robin: It’s good to be able to have projects fund themselves. Double dipping is obvious, but it’s also fine, probably not so heavy. When DF comes, there will be fewer of these. If I’d try to aggressively abuse this system, I’d get OPF to pay me to create the data.
- Tobias: suggest add rule: if get $ from unleash data to create datasets, then if team comes back to the DAO for grant requests, then deduct DF rewards from grant request. 
- Trent: how to implement? Might be hard
- Trent: if we did go back to par on this, good to communicate the expectations. "Unleash data" was never meant to be only to "get a grant to construct/improve your own handful of datasets, to sell". It had (and has) broader intent, such as: become a data broker to get data owners' data into Ocean Market, integrate Filecoin & publish on Ocean Market, etc
- Tobias: datapoint: first commercial dataset on Acentrik was funded by the DAO. We left a good impression there. This is the first return of the dataset funding back to the ecosystem.
- Robin: plus the C2D stuff on Tobias’ datasets (Evotegra)
- Roberto: I’m happy to open this up. Important to guide projects towards constructive outcomes. I fear that as we invest in datasets, we shoot some cannonballs rather than try different things. I’d hope that it funds other activities: rather than gathering / sharing / data, it’s for things like data union models for people to join the dao. Or rather than paying for the data, we move into models perhaps working tech for people to gather the data. Move towards mining and providing right incentives for participants to share the data. “Fire bullets, not cannonballs”
- Trent: I would personally love to see the 20,000 OpenML datasets and 1000 HuggingFace datasets and models
- Robin: but these are open
- Trent: yes. But USP when combine with C2D (priced compute)
- Roberto: be more broad. Some models aren’t ready to be consumed for data science. Would be great to have a bunch of data from various subgraphs of TheGraph into here. This would take a lot of effort to put together. Eg I saw a group that dumped all mirror from Arweave into a repository. I really want to promote us having more integrations, raw data or otherwise, to provide the supply where the rubber meets the road. Bullets not cannonballs.
- Tobias: my approach is looking through glasses of AI company, from perspective of potential consumers. Useful to have a handful of promotional datasets.
- Trent: flames are around speculation (datasets about datasets, datasets about NFT speculation), let’s incentivize that more
- Roberto: +1 to the above. Many of us are in many OceanDAO WGs. We’re in a good position to provide good feedback, continuously shepherding initiatives. 


- Q: if make “unleash data” par again (same conditions as other categories), and communicate the expectations that it’s more broad (see above), any objections? 
- Tobias: in time we have to adjust by DF rewards

----

- **Q: if make “unleash data” par again (same conditions as other categories), communicate the expectations that it’s more broad (see above), and update before DF, any objections? (no objections raised)**

- **Decision: make “unleash data” par again (same conditions as other categories), communicate the expectations that it’s more broad (see below), and update before DF, any objections**
- **Expectations to communicate:** 
  - _"Unleash data" has actually always had a broad intent, towards driving Data Consume Volume. It is intended for projects like: become a data broker to get data owners' data into Ocean Market, networking / “hitting the phones” to increase consumption on Ocean Market, integrate Filecoin & publish data on Ocean Market, etc. Here are further examples. It was never meant to be solely for constructing / maintaining a small number of datasets._
  - _Whatever is proposed should be high value-add to the Ocean ecosystem. Example of poor value-add: requesting a lot of OCEAN to construct / maintain a small number of datasets to sell with expectation of profit. We expect and encourage OceanDAO voters to downvote such proposals._
