### ISSUE TITLE
[Parameters & Roadmap WG] Is 3k a good amount to onboard new projects, or is this too low?

### ISSUE THREAD

**Issue by idiom-bytes** [oceanprotocol/oceandao#74]
**Discord poll:** https://discord.com/channels/612953348487905282/908016760190537798/920224355592581150

**Background / Motivation**
Currently, the first grant for participants sits at 3k. 

There have been concerns expressed that 3k is too small, and this may not allow for teams to enter the grant program.

**For 3k:**
- This enables voters to more easily vote New Participants into the grants program.
- This enables a large range of New Participants to engage with the grants program.

**Against 3k:**
- This is too small, and will force more prominent New Participants away from the grants program.
- A higher amount for New Participants has been accepted by voters many times in the past.
- Project-Guidance WG should be able to onboard New Participants and make adequate recommendations.

**Comment by w1kke** [comment]
I see the 3k as taking a seat at the table of the OceanDAO, getting acquainted with the process of voting & proposing as well as requesting the funds etc.
And then using the 3k to also showcase their own project more via a website or a technical architecture that will include Ocean Protocol and the ecosystem. Develop a UI+UX mockup etc.
After they have done that they are ready to showcase their project and ask for funding to make their ideas reality if the community supports them.

**Comment by TimDaub** [comment]
> There have been concerns expressed that 3k is too small, and this may not allow for teams to enter the grant program.

Have those concerns been made public? Who were they from and why should we care? IMO, we should only care if they come from actors we know 100% for sure that they won't abuse those funds but instead deliver on them.

**Comment by idiom-bytes** [comment]
Poll on Discord for this topic [can be found here](https://discord.com/channels/612953348487905282/908016760190537798/920224355592581150).

**Comment by trentmc** [comment]
Datapoint: for R12, 15 first-time projects and 13 returning projects.

**Comment by trentmc** [comment]
The Parameters & Roadmap WG met yesterday to finalize this issue. Discord votes are taken as an input sentiment, not as the final say. The final say is in the WG.

- Discord votes: 8 to “hold” at 3k, no votes for other

- Discussion:
  - Roberto: note that this may be limiting for bigger projects
  - Tobias: how can a project present itself with just 3K?
  - AlexC: simple. Roadmap w milestones. Prove yourself
  - Roberto: lots of ways to be creative

- **Q: any objections to hold at 3k? (none raised)**
- **Decision: hold at 3k**
