### ISSUE TITLE
[Parameters & Roadmap WG] Choose funds for R13, subject to pre-set budget

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/oceandao#76]
**Discord poll:** https://discord.com/channels/612953348487905282/908016760190537798/920233804663259186

**Is your feature request related to a problem? Please describe.**
R11 and R12 had 500K OCEAN available. In both rounds, there were fewer than 500K OCEAN worth of proposals. Eg in R12 there were 222K OCEAN worth. 

Therefore, there was no competition among teams: if you had > 50% votes then you got funding. More competition among teams helps quality of proposals.

**Describe the solution you'd like**

Choose a funding approach / amount that helps drive proposal quality. This means: ensure sufficient competition.

This is subject to a pre-set budget (upper bound) of 200K.

Note: this description was updated on 20211208 based on budgets. Details in [this comment](https://github.com/oceanprotocol/oceandao/issues/76#issuecomment-988556802).

**Comment by tmanthey** [comment]
Funding is just one of many DAO parameters. I'd say that the wg should adapt the funding parameters of R13 after the R12 results including the other parameter changes for R13.

**Comment by tmanthey** [comment]
I strongly support (bias alert) to treat "unleash data" category as any other category until Ocean V4 including data farming is actually established and its effects are understood rather than guessed. 
Reminder: Funding of "unleash data" requested in R10 was almost 200k USD. In R11 it was 6k. If we reestablish "unleash data" this has a major impact on the funding.

**Comment by w1kke** [comment]
I would propose to make the size of the pool dynamic:
Set the next amount to be available to 90% off the requested amount in the last round. This will automatically cause competition even if only the same projects apply again (they might go for the next step to get more funding).
This will also make the earmarks more interesting.
So this means that the amount of the $OCEAN will be dynamic from round to round.

**Comment by tmanthey** [comment]
> I would propose to make the size of the pool dynamic: Set the next amount to be available to 90% off the requested amount in the last round. 

I agree. This will create a default squeeze independent from the utilisation of the maximum grant amount. This is a parameter to control the quality of proposals. Hence I would adjust that percentage to the perceived quality of the projects in the DAO. e.g. low quality, high default squeeze and vice versa.

**Comment by TimDaub** [comment]
> R11 and R12 had 500K OCEAN available. In both rounds, there were fewer than 500K of proposals. So there was no zero-sum competition among teams: if you had > 50% votes then you got funding. More competition among teams helps quality of proposals.

Algorithm:

1. Define funding ceiling as e.g. 500K OCEAN, let's call it `fundingCeiling`
2. Get OCEAN/USDC price ticker
3. After the deadline for submission has passed; convert all requests from USD to OCEAN and sum them up; let's call it `totalRequest`
4. `If (totalRequest > fundingCeiling): available = fundCeiling; // (so 500k OCEAN)`
5. `else: available = totalRequest * 0.7 // so if we have less requested OCEAN, we artificially lowe the funding ceiling such that only 70% of all requested funds get allocated to provoke competition`

**Comment by trentmc** [comment]
These are great ideas re dynamic sizing.

From some discussions inside OPF in the last week, around monthly budget:

- Maximum funding is a special parameter because it's first and foremost a _budget_ item, whereas most others are incentives. As a budget: 51% schedule. For now, to avoid conflict-of-interest and to be more realistic wrt actual OCEAN resource availability, OPF will set it. 
- Then, 200K OCEAN budget starting in R13. 
- _This_ WG has power to set a lower cap on a round (<= budget), towards sufficient competition etc. This could be dynamically set.

We discussed this in the yesterday's Parameters & Roadmap WG meeting.

So, let's use _this_ GH issue to discuss setting of a lower cap on a round.

As a datapoint, there was a total of 199725 USD requested for R12 [[Ref](https://www.notion.so/Round-12-Proposals-eb26b46ac9b74604a108049ed7892a9a)]. As of today, 1 OCEAN is 0.90 USD [[Ref](https://www.coingecko.com/en/coins/ocean-protocol)].

**Comment by TimDaub** [comment]
> Therefore, there was no competition among teams: if you had > 50% votes then you got funding. More competition among teams helps quality of proposals.

Btw. I think this issue might have a false premise assumption. Competition during voting isn't a proxy for teams doing better work.

Indeed, for RPI, we actually just stop all work for 1 week to write the proposal and generally I consider most of the work quite wasteful. It'd be much better if we could just get money. Besides, e.g. for R12, I made our proposal A+ for the same reason as always: To get a mega high chance of receivih funding.

But voting is decoupled. You might as well just know some whales that vote for you without doing any significant votes. Or you get a shoutout from team members. But there's no direct connection between e.g. marketcompetition where two companies compete for the same customers and voting competition.

**Comment by idiom-bytes** [comment]
Based on this issue & discussions, the budget has been set for R13.

You can find the official task responsible for implementing the parameters here:
https://app.zenhub.com/workspaces/oceandao-60a669231c2ed7000e90684b/issues/oceanprotocol/oceandao/63

They are as follows:
New Entrants: 24k
New Outreach: 12k
Core Tech: 30k
General: 134k
Total: 200k OCEAN

**Comment by idiom-bytes** [comment]
Poll on Discord for this topic [can be found here](https://discord.com/channels/612953348487905282/908016760190537798/920233804663259186).

**Comment by trentmc** [comment]
The Parameters & Roadmap WG met yesterday to finalize this issue. Discord votes are taken as an input sentiment, not as the final say. The final say is in the WG.

- Discord votes: 9 for “pre-set budget”, 3 for “% based on last round”, 1 for “WG sets lower cap”

- Discussion:
  - Robin: I had suggested the idea “% based on last round” but now that 200K budget, keep it at that
  - Roberto: I’m happy with either 1 or 2
  - Trent: I’m happy with either 1 or 2
  - Alex: pre-set budget, with the assumption that this WG does it each round
  - Trent: lean to what Alex said
  - Robin: I’m happy with either. From a programming sake, 1 is better. We can adjust
  - Tobias: I wished the changes in funding would have been smoother. We went up dramatically, now going down dramatically. Bad for stability, reliability, perception
  - Trent: datapoint: each of the last two rounds requested approx 200K OCEAN. 

- **Q: if set funding at pre-set upper bound, with the understanding that this WG will meet and set it each round subject to budget, any objections? (No objections raised)**
- **Decision: set funding at pre-set upper bound**
