### ISSUE TITLE
Allow everyone to make snapshotorg proposals

### ISSUE THREAD

**Issue by TimDaub** [oceanprotocol/oceandao#82]
Today, the Parameters group is organizing a vote in Discord, which I find an odd choice for a tool that is not made for voting. Link here: https://discord.com/channels/612953348487905282/908016760190537798/920257683645411368

e.g.

<img width="649" alt="Screen Shot 2021-12-14 at 11 51 01" src="https://user-images.githubusercontent.com/2758453/145984489-b4655ce3-d5af-486d-ad0f-997d44385886.png">

Whereas it seems snapshot.org would be a great place for exactly this type of decision-making. So I just wanted to copy over all the proposals to snapshot org and have everyone vote there. But when I clicked on "Create new proposal" and entered all my data, the page told me that only as an author of the space, do I have permission to create one:

<img width="661" alt="Screen Shot 2021-12-14 at 11 49 38" src="https://user-images.githubusercontent.com/2758453/145984608-164c736c-23f7-446a-a2af-869329c7909e.png">

Pls allow everyone to create snapshot org proposals so that we can simply have people vote on their site if we have governance questions.

**Comment by idiom-bytes** [comment]
Polling:
- Discord was used for this poll as part of the Parameters & Design Process outlined by the WG.
https://docs.google.com/document/d/1CGqLJgWKwzDlZFgA7FPmkyRaZHmorutMv-GaSroMSPw/edit#heading=h.a1v0x4spw3ns

Snapshot:
- Snapshot was not used intentionally, as this polling is meant to be used as sentiment/signal to arrive at a decision.
- Snapshot is therefore continued to be utilized for official decision making, specifically for grant allocation.

I propose this issue to be closed.

**Comment by TimDaub** [comment]
Discord is a bad choice as it's not made for this type of voting.

**Comment by idiom-bytes** [comment]
This is just for sentiment Tim. It is not meant to be official or an outcome, but one of many sources of information taken into consideration in the decision-making process.

These are fairly deep-in-the-rabbit-hole discussions. If people really want to play a part in the decision-making process, we want to welcome them into the GH discussions and the Working Group.

**Comment by w1kke** [comment]
I have setup a clone of the voting system of the OceanDAO - it has the same strategies in place. If you want to run a poll on that @TimDaub, I am more than happy to host you and the poll:
https://snapshot.org/#/voting.robinlehmann.eth/

**Comment by DMats** [comment]
I've seen many other DAOs use the free tier of https://sesh.fyi/ for polls in Discord (aka. sentiment checks, temperature checks).

**Comment by trentmc** [comment]
For the decisions that a given WG needs to make, the WG typically makes them via their weekly or bi-weekly mtgs. Sometimes in Discord, but mostly in the mtgs. More tooling isn't needed, at least not at this stage. Closing.
