### ISSUE TITLE
Ideas for Improving the application experience for Core-Tech Proposals

### ISSUE THREAD

**Issue by drprk** [oceanprotocol/oceandao#87]
In need of addressing the following problems.

- Effective guides for core-tech proposals to come-in and remove friction for coming up with newer proposals/ideas, especially for newer entrants. 
- Also have the guides posted on the Medium content under content of Core-Tech 

- **Outside scope of core tech WG:** Improving UX on moving through docs & tutorials [Although it is WIP}

**TLDR version:**

- A reference article for each Core-tech earmarked deliverable. Example: To deliver Core-tech integration for DeSo models powered by Ocean, what are the Providers that should be touched upon. etc. A reference article will help for teams to understand the core requirements before taking up the project. Similarly for Decent. Storage, V3C credentials etc
- Inviting external bloggers/Ocean Ambasssadors to write about Core-Tech deliverables
- Inviting other DAOs to collaborate on Core-tech proposals [D2D route]

### Problem Description & Solution brainstorming

Although some improvements are being discussed under Core-Tech WG already, the following solutions could be a worthy adds.

- Placement of Ocean Protocol documentation on medium posts under CoreTech paragraphs. Will be a lot easier for Devs & builders to navigate while reading up on Core Tech proposals. Improvement will be further as Akshay continues to work on the same through CleanDocs project

- Discussion of Improving the earmark to 5k for Core-Tech in comparison to others (Justification: Lack of entries on previous rounds)

**UX for Core-tech documentation:**

- Plausible Visual change: Dark-mode feature request on main-site :) , especially for https://docs.oceanprotocol.com/tutorials/introduction/

### Other Alternatives

- Public explanation of the benefits that external teams get in terms of working on Core Tech proposals. **Ex:** In addition to the PR expressed on social media sites etc, Mention of the services on Ocean main site viz. First class integration of Decentralized storage networks (once they are successfully shipped)

- Inviting Ocean Ambassadors, external bloggers to exclusively write about Core Tech proposals (Successful Referral bonus to incentivize the content writers)

- Explore D2D routes (Speak to other social DAOs for inviting proposals on Core Tech - Special referral bonus for DAOs on successful applications)

**Additional info on:**

- Core Tech WG-document
- Core Tech Discord.

**Comment by drprk** [comment]
https://docs.google.com/document/d/1a7Z_nNlbYluTRA4p4zKYWfEzH7hjZjVx0ak3Z_I1J34/edit?usp=sharing

**Comment by trentmc** [comment]
We're in decent shape on this now, there are a few paths as the wiki lays out
