### ISSUE TITLE
Suggestion for Ocean Academy Contents | Q1 2022

### ISSUE THREAD

**Issue by drprk** [oceanprotocol/oceandao#90]
## Problem Description

- A Missing hook, after completion of the Ocean Academy
- Ocean ambassadors, post their completion of the short-course content could have an opportunity to 

## Proposed Solution

With the current CMS for Ocean ambassadors going through an overhaul, I believe there is room for feature enhancements in terms of opportunities posted by Project Working groups.

**Ex:** Grant winners can post their earning opportunities for marked tasks to earn in Ocean

This gives an opportunity for ambassadors to be more involved in earning on tasks following the Ocean Academy completion, similar to how it's done for Ocean Ambassadors through Trello communication.

## Complementary routes:

- Process to be complemented into the upcoming Website management, post-completion of Ocean Academy
- Establish a mechanism for Grant winners to post opportunities & short term bounties to get involved in other projects to complement their visibility of being an Ocean Ambassador
- Funneling from Townhall to shoot awareness on Ocean Ambassadors - earning opportunities
- Opportunities to be advertised on Ocean Academy Twitter channel

**Additional context**

This process ensures that there is retention of potential Ocean ambassadors willing to make a contribution to the Ocean ecosystem.

**Comment by trentmc** [comment]
OceanDAO is not the place for giving this feedback, please bring this to the Ocean Academy folks
