### ISSUE TITLE
[DAO] Establish DAO-DAO relationship w/ Legal Ecosystem-DAO (example: LexDAO)

### ISSUE THREAD

**Issue by idiom-bytes** [oceanprotocol/oceandao#91]
We are increasing the overlap of issues we're encountering in the DAO, w/  projects that receive grants, in addition to infrastructure that we deploy such as the automation of funding between OPF & grant recipients.

Even if we come up with some ideas/solutions, we do not have adequate channels in place to validate these decisions/architectures. 

I believe someone who is focusing on legal relationships in OceanDAO should write a grant proposal to establish a relationship with LexDAO and Utopia Labs, to increase DAO/LLC integrations within OceanDAO to unlock participants from their restrictive jurisdictions.

This means participants in OceanDAO would be able to access knowledge & tooling that empower them to endeavour towards Web3 solutions without being bounded by their geography. Currently, German participants such as RPI as an example are restricted from launching ERC-20, financial products, performing more advanced forms of raising capital like funding retroactive public goods.
I propose in the near future to expand OceanDAO relationships with LegalDAOs (LexDAO) & InfrastructureDAOs (Utopia Labs / Near) who may be able to provide the support that unlocks Ocean Ecosystem individual contributors, teams, and orgs, with the required know-how to make them jurisdiction agnostic.

Legal is a deep vertical, and I would love to identify the right person inside OPF to continue stewarding & bridging legal initiatives across OceanDAO and other DAOs (LexDAO). Or in this case, establish initial grants to incorporate Ecosystem DAOs like LexDAO into the network to start scaling data-friendly initiatives that are DAO-native, and jurisidiction-agnostic.

Example:
- [ ] Grants-Friendly DAO Deployer (Modified-MCV) that can easily structure a DAO that maps to requirements inside Ocean Ecosystem
- Can deploy DT's
- Can emit ERC20's
- Is retroactive-funding friendly

- [ ] Self-Sovereign Data-Friendly Data-Union Deployer  that can easily:
- Create a self-sovereign entity where each participant owns their data
- Can deploy ERC2
- Can deploy DT
- Can monetize, buy, access, deploy models, etc... for data owned

**Comment by drprk** [comment]
Big fan of DAO2DAO working relationships. In fact it could be a great product going forward. D2D is the future of DAO growth strategies. Lot of social DAOs come to mind.

Some quick thought from --> https://vitalik.ca/general/2021/08/16/voting3.html

Picking some excerpts from here, below

![image](https://user-images.githubusercontent.com/88657058/146829541-7c615dc3-4cc3-4433-a5b4-cacce277a844.png)

BrightID kind of fits the following

>  Self-Sovereign Data-Friendly Data-Union Deployer that can ....

Have a few more thoughts on DAO collaborations, more on that in later discussions.

**Comment by drprk** [comment]
On possible DAO relationships outside of our current networks, I propose/recommend SuperTeam DAO ~ a bustling Solana DAO that has proven proof of shipping for a lot of initiatives. 

Website: https://superteam.fun/ 
Proof of Shipping: https://twitter.com/SuperteamDAO
Initiatives that we can outsource by collaboration (initiatives that are beyond the scope of OPF core/DAO projects)

- Integration with Solana network. [Reason: Increased traction by engaging with the Solana community ]
- Products from Ocean-tech to deploy onto the Solana Network
- Exciting projects from Solana network to function with Ocean DAO ecosystem [DeSo apps, Payment stream dApps ]

**Caveats**: 

- This could be a medium-to-long project given there's no current integration
- Possible ongoing thesis that Ocean already has a general, low gas-fee option with Polygon, it would seem that Polygon would be sufficient hence this initiative might take a lower priority initiative. However, we could still drive low priority traction by collaborating with different network Social DAOs to diversify community tractions and build on D2D initiatives.

**Opportunity:** https://superteam.fun/expand-to-solana

http://docs.neon-labs.org

Neon Labs ensure that existing EVM-compatible smart contracts could be ported to enable dApps on Solana to function with Ethereum standards.

**Note:** Technical corrections are welcome

**Comment by trentmc** [comment]
This would be nice but it's not gonna happen anytime soon. Potentially huge overhead, and extra liability to OceanDAO. Best thing is to simply direct people as needed to LexDAO etc.
